### ISSUE TITLE
JsonValue equality

### ISSUE THREAD

**Issue by bergey** [fsharp/FSharp.Data#1006]
Equality for `JsonValue.Record` depends on the order of keys.  I expect two objects with the same keys & values to be the same regardless of key order.  Would you take a PR with an equality predicate that ignores order of keys?

**Comment by ovatsus** [comment]
It used to be like that originally, and we even used a map, but we had to change it to an array of tuples to preserve the order, as some applications break if you don't use a specific order of keys
