### ISSUE TITLE
Object reference not set to an instance of object for IMDB URL

### ISSUE THREAD

**Issue by sgronblo** [fsharp/FSharp.Data#1007]
Environment:

OS: OSX 10.11.6
Editor: VSCode 1.7.1
Plugin: Ionide-Fsharp 2.10.1
Compiler environment: Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/08fd525 Thu Nov 10 20:28:28 EST 2016)

I wanted to try to use HtmlProvider. I tried to set it up like this by using the IMDB top 250 movies ranking:

```
module GetWiki
open FSharp.Data

type ImdbRanking = HtmlProvider<"http://www.imdb.com/chart/top?ref_=nv_mv_250_6">

[<EntryPoint>]
let main argv =
    0 // return an integer exit code
```

However VSCode shows an error on the first line saying: internal error: Object reference not set to an instance of object.

If I uncomment the line with the HtmlProvider the error goes away.

**Comment by ovatsus** [comment]
Just tried it on current master and it works for me
