### ISSUE TITLE
Nuget example in documentation does not work

### ISSUE THREAD

**Issue by sgronblo** [fsharp/FSharp.Data#1008]
Environment:

OS: OSX 10.11.6
Editor: VSCode 1.7.1
Plugin: Ionide-Fsharp 2.10.1
Compiler environment: Mono JIT compiler version 4.6.2 (mono-4.6.0-branch/08fd525 Thu Nov 10 20:28:28 EST 2016)

Trying to use type providers in F#. Following the NugetData example here: http://fsharp.github.io/FSharp.Data/library/HtmlProvider.html

I type in everything as in the example but when typing `let rawData = NugetStats().` I just get a looong list of useless completion entries. I noticed that if I type a character and delete it and then press ctrl+space I can make the expected Html, Lists and Tables show up. However, even if I enter `let rawData = NugetStats().Tables.` I don't get any Table name suggestions to show up no matter what I do.

**Comment by ovatsus** [comment]
That's an autocomplete issue in vscode
