### ISSUE TITLE
Need to reopen FSharp.Data

### ISSUE THREAD

**Issue by gmpl** [fsharp/FSharp.Data#1013]
I need to get the type of the rows because I will transform the structure later, as you can see in this sample code:

    #r @"C:\packages\FSharp.Data.2.3.2\lib\net40\FSharp.Data.dll"

    open FSharp.Data

    type InterestRate = {Period : string; Mid : float}
    type html = FSharp.Data.HtmlProvider<"http://www.cmegroup.com/trading/interest-rates/stir/eurodollar.html">

    open FSharp.Data

    let allRows = html.Load(@"http://www.cmegroup.com/trading/interest-rates/stir/eurodollar.html").Tables.QuotesFuturesProductTable1.Rows

    type Row = ``HtmlProvider,Sample="http://www.cmegroup.com/trading/interest-rates/stir/eurodollar.html"``.QuotesFuturesProductTable1.Row
    let createIr (row: Row) = {Period = row.Month ; Mid = (float row.Low + float row.High) / 2.}

    let x1 = createIr allRows.[1]

I managed to make it work, but if I don't re-open the namespace (try commenting out the second open) I get a: 

    test-type-prov.fsx(12,16): error FS0039: The namespace or module 'HtmlProvider,Sample="http://www.cmegroup.com/trading/interest-rates/stir/eurodollar.html"' is not defined

BTW : Is there a better way to get the type of the row in order to avoid the 'lookup on object of indeterminate type error' ?

**Comment by tpetricek** [comment]
You can refer to the type using the name that you give it when you say `type Xyz = HtmlProvider<...>`. Using `CmeEuro` as the type name:

```
open FSharp.Data
type CmeEuro= HtmlProvider<"http://www.cmegroup.com/trading/interest-rates/stir/eurodollar.html">
type Row = CmeEuro.QuotesFuturesProductTable1.Row
```

You can refer to the row type using `CmeEuro.QuotesFuturesProductTable1.Row`.

**Comment by gmpl** [comment]
Thanks for your answer wrt to my last question.
What about the main question?
