### ISSUE TITLE
Preserving whitespace with Load

### ISSUE THREAD

**Issue by imranazad** [fsharp/FSharp.Data#1017]
How can I specify the following option:

    LoadOptions.PreserveWhitespace

with the Load function? I've tried passing it in but the compiler complains there's no such overload.

**Comment by imranazad** [comment]
Any one?

**Comment by imranazad** [comment]
Hi,

Is there any solution for this?

**Comment by ovatsus** [comment]
I didn't understand what was the issue. What Load function are you referring to, and whitespace do you want to preserve?

**Comment by imranazad** [comment]
It's with regard to this method in Runtime.fs:

` static member Create(reader:TextReader) =    
     use reader = reader
     let text = reader.ReadToEnd()
     let element = XDocument.Parse(text).Root 
     { XElement = element }`

I've had to pass LoadOptions.PreserveWhitespace to the `Parse` method. I want to be able the preserve the whitespace in the source XML when it's parsed. I was wondering if there was a way to do it via the client API rather than having to manually hardcode this in as I've had to fork the repo.

**Comment by ovatsus** [comment]
Oh, I see. Why do you need to pass it, is it just for debugging purposes or some other reason?

I guess it would be safe to always pass LoadOptions.PreserveWhitespace, so I'd rather do that than add yet another option. Do you want to send a PR for that?

**Comment by imranazad** [comment]
>  guess it would be safe to always pass LoadOptions.PreserveWhitespace,

Yes that's what I was thinking too. The main reason is we have an XML feed that we process and generate a website from and we want to preserve the white-space in the XML content as it's necessary in order to render the content correctly.

Sure thing I'll send a PR through.

**Comment by ovatsus** [comment]
But the whitespace on the contents should always be preserved anyway, this flag is just to present the whitespace around tags used for indentation

On 11 Apr 2018 12:05, Imran Azad <notifications@github.com> wrote:

guess it would be safe to always pass LoadOptions.PreserveWhitespace,

Yes that's what I was thinking too. The main reason is we have an XML feed that we process and generate a website from and we want to preserve the white-space in the XML content as it's necessary in order to render the content correctly.

Sure thing I'll send a PR through.

**Comment by imranazad** [comment]
> this flag is just to present the whitespace around tags used for indentation

That's right we need to preserve the indentation around tags, not specifying this flag renders elements conjoined. For example if you have the following xml

`<tag>Paracetamol</tag> <tag>is</tag> <tag>a</tag> <tag>drug.</tag>`

We want it to render as

`Paracetamol is a drug.`

Without preserving white space we get:

`Paracetamolisadrug.`

**Comment by imranazad** [comment]
@ovatsus here is the pull request: https://github.com/fsharp/FSharp.Data/pull/1157

Please let me know if there's anything else I need to do.

**Comment by chunter** [comment]
@ovatsus would you be so kind as to take a look at the pull request mentioned above - we would really like to be able to use the main branch of your code again, but we need this fix. Thanks
