### ISSUE TITLE
HtmlProvider Self closing table tags

### ISSUE THREAD

**Issue by arctiq1** [fsharp/FSharp.Data#1022]
HtmlProvider doesn't provide tables if they contain self closing tags which are not closed.

[According to w3.org HTML 4.01](https://www.w3.org/TR/html401/struct/tables.html#edef-TD) and [HTML 5](https://www.w3.org/TR/html5/tabular-data.html#the-td-element) TD, TH TR tags needn't be closed. Sadly many apps take advantage of this.
 ## Expected
Parsing self closing tags should behave the same regardless of whether the tags are closed.
 ## Sample error throwing code
```fsharp
// Missing </th>, </tr> and </td>
let [<Literal>] Example = """
<!DOCTYPE html>
<html>
  <body>
    <table>
      <tr>
        <th>Number
        <th>Text
      <tr>
        <td>4
        <td>Hello
    </table>
  </body>
</html>"""

type NotWorking = HtmlProvider<Example>
(NotWorking.GetSample()).Tables.Table1.Rows
```
Fails with
```
Error #39 - The field, constructor or member 'Tables' is not defined at line 27 col 25
```
 ## Sample working alternative
```html
<!DOCTYPE html>
<html>
  <body>
    <table>
      <tr>
        <th>Number</th>
        <th>Text</th>
      </tr>
      <tr>
        <td>4</td>
        <td>Hello</td>
      </tr>
    </table>
  </body>
</html>
```

The html files are equal, but the second works while the first one does not.

**Comment by thinkbeforecoding** [comment]
I fixed it with PR #1061.
The PR also fix the <ul><li>a<li>b</ul> case.
