### ISSUE TITLE
FSharp.Data.Runtime.Caching.createInMemoryCache memory leak

### ISSUE THREAD

**Issue by FreeBirdLjj** [fsharp/FSharp.Data#1024]
The implementation of `FSharp.Data.Runtime.Caching.createInMemoryCache` stores the outdated value forever and GC cannot release their memory.

**Comment by giacomociti** [comment]
if I understand correctly, #983 includes a fix for this

**Comment by FreeBirdLjj** [comment]
Sorry for duplicated issue, I just searched the keyword `createInMemoryCache` and found no results so I open this issue.
