### ISSUE TITLE
Json Type Provider Parse should return option

### ISSUE THREAD

**Issue by nojaf** [fsharp/FSharp.Data#1026]
If you try to parse a json string that is missing a property an exception will occur.
F.ex.
```fsharp
#r @"..\..\packages\FSharp.Data.2.3.2\lib\net40\FSharp.Data.dll"

open FSharp.Data

type Foo = JsonProvider<"""{"foo":1}""">
Foo.Parse("{}").Foo
```
And if you are not in control of the incoming json this is a problem. There no way of telling if the json coming from a client will match.

Would it not make sense if the Parse function returns an option of Root?

**Comment by ovatsus** [comment]
There is a TryParse

**Comment by akdor1154** [comment]
There is no `TryParse` on JsonProvider, only on JsonValue. Can you re-open this?
