### ISSUE TITLE
CSV type provider parses as Int32 values which are larger than Int32

### ISSUE THREAD

**Issue by lilred** [fsharp/FSharp.Data#1034]
10-digit phone numbers are inferred by the type provider as Int32 values. This causes a runtime error when trying to read a row.

**Comment by ChrisBallard** [comment]
Is this one still an issue? I've just attempted to create a failing test for this, but seems int64 is correctly inferred should any sample value of 2147483648 or over exist. Of course if the number is formatted like a phone number (e.g 214-7483-648) then string is inferred.

**Comment by lilred** [comment]
Sounds fixed to me I guess. Thanks whoever did this =)
