### ISSUE TITLE
Overall slowness in XAMARIN

### ISSUE THREAD

**Issue by FaguiCurtain** [fsharp/FSharp.Data#1037]
I'm using FSharp.Data CSVProvider and JSON Provider on MACOS X, Xamarin 6.15

I'm experiencing a lot of slowness from Xamarin when i use the library (compile and F# interactive at the same time)
the cursor becomes round and waits for a few seconds, as it looks like its trying to read all the files to check whether they were modified or not. 
i've got around 20 files who are part of a CSVtype or JSONtype but they are not very big, its just a few excel spreadsheets with time series.

its quite annoying and prevents me from working normally. I'm pretty sure the issue is with the library because if i use another solution, everything looks fine

**Comment by ovatsus** [comment]
A big perf improvement was just merged to master
