### ISSUE TITLE
Doesn't build on a machine only with VS2017

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#1041]

**Comment by ovatsus** [comment]
And can't find VS2015 community to download any more :(

**Comment by ovatsus** [comment]
Installing Visual F# 4.0 Standalone also didn't help

**Comment by ovatsus** [comment]
1) Building C:\Git\FSharp.Data\FSharp.Data.sln failed with exitcode 1.
          2) MSB4057: C:\Git\FSharp.Data\src\FSharp.Data.fsproj(0,0): The target "Rebuild" does not exist in the project.
          3) MSB4019: C:\Git\FSharp.Data\src\FSharp.Data.Portable7.fsproj(86,3): The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\FSharp\Microsoft.Portable.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
          4) MSB4019: C:\Git\FSharp.Data\src\FSharp.Data.Portable259.fsproj(86,3): The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\FSharp\Microsoft.Portable.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
          5) MSB4057: C:\Git\FSharp.Data\src\FSharp.Data.Portable47.fsproj(0,0): The target "Rebuild" does not exist in the project.

**Comment by eriawan** [comment]
@ovatsus 

> And can't find VS2015 community to download any more :(

The web download of VS 2015 Community Edition is available at free sign up of Visual Studio Dev Essential. Just sign up at this link:
https://my.visualstudio.com/Benefits?wt.mc_id=o~msft~vscom~devessentials-swimlane~689&campaign=o~msft~vscom~devessentials-swimlane~689

After your email has been verified, please log in to my.visualstudio.com, 
Your screen should look like this:

![image](https://cloud.githubusercontent.com/assets/8773147/24890004/89149d8a-1e97-11e7-83f3-c722441c5d19.png)

Then search for download of VS 2015 Community Edition Update 3 web download.
The link is: https://my.visualstudio.com/Downloads?PId=2226

Your screen should look like this:
![image](https://cloud.githubusercontent.com/assets/8773147/24890102/16d69ac4-1e98-11e7-916b-a6f607f346f6.png)

Let me know if you still can't download it.

**Comment by ovatsus** [comment]
Thanks, I already got VS 2015, but we still need to fix the project so it works either if vs2017 or vs2015 is installed, without requiring a specific one

**Comment by Thorium** [comment]
I had similar issues with another fsharp project.

I thought that the problem is fsproj-file:
```fsharp
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
```

But modifying that didn't fix my problems. What helped for me was updating FAKE, maybe MSBuild command parameters have changed... But I tried this with FSharp.Data, didn't help.
(Also I had problem with my FSharp.Core reference, I had do change it to explicit reference to project.references and come from Paket.)

**Comment by eriawan** [comment]
@ovatsus 

I have a machine that only has VS 2017 installed, and it works fine.

My VS 2017 release is: 2017.2 iteration 16.

This is the about box of my Visual Studio:
![vs2017_about](https://user-images.githubusercontent.com/8773147/28501514-611e8234-7007-11e7-8fb3-61b4a468e136.png)

**Comment by eriawan** [comment]
@ovatsus 

I think this issue can be closed, because I have tested on different VM and physical machines. 
If you have other issues about compiling in VS 2017.2, please let me know and I hope I can help out 🙂

**Comment by eriawan** [comment]
@ovatsus 
is this issue still happened?
I have tested on VS 2017.2 and VS 2017.3 (the updated 15.3.3) it works well.

**Comment by realvictorprm** [comment]
I would like to know the state too.

**Comment by ovatsus** [comment]
Still doesn't work for me. If I only have VS2017 installed, then I have to revert this for the Fake build to work - https://github.com/fsharp/FSharp.Data/pull/1045 - and if I do that I get a bunch of errors like `The module/namespace 'System.Collections.Generic' from compilation unit 'mscorlib'`

Installing just the MSBuild Tools 2015 fixes compilation for the main version, but portable still fails, so I'm forced to actually install VS2015 for it to work

**Comment by Thorium** [comment]
Just took the latest master. On my VS2017 v15.3.4 the solution file builds ok. However admin developer command prompt command line `build All` fails with 

```
MSB4057: C:\git\FSharp.Data\src\FSharp.Data.fsproj(0,0): The target "Rebuild" does not exist in the project.
```

@ovatsus did you find a solution as you closed this?

**Comment by ovatsus** [comment]
That was the same error I was getting before, but after I started referencing FSharp.Core directly from paket it started working for me. Can you try deleting the packages folder and trying again?

**Comment by Thorium** [comment]
A little debugging, the problem is the part of project file I pasted earlier...
```
'$(VisualStudioVersion)' = '14.0'
'$(MSBuildExtensionsPath32)' = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild'
'$(FSharpTargetsPath)' = ''
```
...because path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v14.0\FSharp\Microsoft.FSharp.Targets` doesn't exist.

To display these paths, I just added a Rebuild-task to the project file manually: 
```xml
  <Target Name="Rebuild">  
    <Message Text="VS Version: $(VisualStudioVersion)" Importance="high" />  
    <Message Text="Build path: $(MSBuildExtensionsPath32)" Importance="high" />  
    <Message Text="Target path not found: $(FSharpTargetsPath)" Condition="!Exists('$(FSharpTargetsPath)')" Importance="high" />  
  </Target>
```

**Comment by ovatsus** [comment]
If you have only have VS2017, VisualStudioVersion should be 15 instead of 14, maybe you have a VisualStudioVersion env variable defined?

**Comment by Thorium** [comment]
Setting command environment variable

```
SET MSBuildExtensionsPath32="c:\Program Files (x86)\MSBuild"
```

...before build did help!

**Comment by Thorium** [comment]
Bit off-topic but the latest master is failing one test:

```
1) Failed : FSharp.Data.DesignTime.Tests.SignatureTests.Validate signature didn't change (WorldBank,World Development Indicators;Global Financial Development,True)
  Expected string length 655592 but was 645802. Strings differ at index 129083.
  Expected: "...ndicators).AsyncGetIndicator("GFDD.DI.14")\n\n    member ``D..."
  But was:  "...ndicators).AsyncGetIndicator("FS.AST.PRVT.GD.ZS")\n\n    mem..."
  --------------------------------------------^
at FsUnit.TopLevelOperators.should[a,a](FSharpFunc`2 f, a x, Object y) in d:\GitHub\FsUnit\src\FsUnit.NUnit\FsUnit.fs:line 44
```
