### ISSUE TITLE
XmlRuntime.fs Error with FSharp.Option.Some in xml optional field

### ISSUE THREAD

**Issue by ghost** [fsharp/FSharp.Data#1048]
### Description

i have a simple type generated with Xsd type provider,
then a simple record marked CLIMutable i use as interface from c# client side.
in this way i can construct a record from c# and then use it to generate a new XmlElement to serialize.

My problem is that with the option type, referenced from C# side for some fields of the record, which have minOccur = 0, when i pass an option different from None, like FSharpOption.Some(0.00m) i get runtyme type error exceptions from within the serializer.

the error though comes from original Xml type provider:
**C:\Git\FSharp.Data\src\Xml\XmlRunti
me.fs:line 219**

### Repro steps

Please provide the steps required to reproduce the problem

1. make a library from fsharp side with generated type provider from xsd.
let the xsd have some optional fields. now make a "bridge" record type (CLIMUtable) from FSharp so that when you want to create an istance of the provided type, you create an instance of the bridge record type and pass that on to a function, let's say 

let makeXml (recordType : RecType) : System.Xml.Linq.XElement
makeXml : RecType -> System.Xml.Linq.XElement

2. Reference the library from C# app and try to call makeXml, with all option values set to None, you'll notice no exceptions are thrown.

3. Try to build the recordType instance with at least one optional value set to FSHarpOption.Some(0.00m)

### Expected behavior

providing FSharp<T>.Option.Some(T value) to the RecordType constructor should give no errors to,
and i should be able to get a valid System.Xml.Linq.XElement instance as output.

### Actual behavior

When i try to build the recordType instance with at least one optional value set to **FSHarpOption.Some(value)** 

Here's the exception i get.

```
08:19:49,397 [12] Service - System.Exception: Unexpected value: Some(0.00)
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
   at Microsoft.FSharp.Core.PrintfImpl.go@523-3[b,c,d](String fmt, Int32 len, FSharpFunc`2 outputChar, FSharpFunc`2 outa, b os, FSharpFunc`2 finalize,
 FSharpList`1 args, Int32 i)
   at Microsoft.FSharp.Core.PrintfImpl.run@521[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args)
   at Microsoft.FSharp.Core.PrintfImpl.capture@540[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args, Type ty, Int32 i)
   at <StartupCode$FSharp-Core>.$Reflect.Invoke@720-4.Invoke(T1 inp)
   at <StartupCode$FSharp-Data>.$XmlRuntime.serialize$cont@209(CultureInfo cultureInfo, Object v, Unit unitVar) in C:\Git\FSharp.Data\src\Xml\XmlRunti
me.fs:line 219
```

### Known workarounds

Still have not found a workaround, i've converted options to nullables form fsharp side, with the property attributes [<Optional;DefaultParameterValue(null)>] yet it is still giving me the same error at runtime.

### Related information 

* Windows 8 64 bit
* master

**Comment by ovatsus** [comment]
Xsd provider is not finished yet
