### ISSUE TITLE
'ProviderImplementation.FreebaseTypeProvider error

### ISSUE THREAD

**Issue by MatthiasWeiser** [fsharp/FSharp.Data#1050]
I created a small and simple script. I noticed in VS 2017 the following non-fatal error while developing the script.

> The type provider 'ProviderImplementation.FreebaseTypeProvider' reported an error: The type provider constructor has thrown an exception: Type 'FSharp.Data.Runtime.Freebase.FreebaseDataContext' not found in ["C:\Users\Dell\Documents\Visual Studio 2017\Projects\OptionsOutUpload\packages\FSharp.Data.2.3.3\lib\net40\FSharp.Data.dll"]	

I have downloaded the latest FSharp.Data using Nuget.

> package id="FSharp.Data" version="2.3.3" targetFramework="net452" 

It would be nice if this error can be removed. If you point me in the right direction, then I might do it myself.

**Comment by MatthiasWeiser** [comment]
The search for Freebase in the code did not yield any results, thus it might be related to the build process.

**Comment by ovatsus** [comment]
The freebase provider was removed a long time ago, so this is very weird :) Maybe you have an older FSharp.Data.dll around that's being loaded at runtime?

**Comment by MatthiasWeiser** [comment]
It is just an Visual Studio. Weird - but will close.
