### ISSUE TITLE
Please update ProvidedTypes.fs for Mono 5.0 

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Data#1054]
Please update to use the latest version of ProvidedTypes.fs, as described in  https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121

**Comment by baronfel** [comment]
This should be in fixed in PR #1056 as well as part of a general paket update

**Comment by baronfel** [comment]
This can be closed now, I believe.
