### ISSUE TITLE
FSharp.Data.HtmlDocument.Parse br element

### ISSUE THREAD

**Issue by Peter360** [fsharp/FSharp.Data#1059]
HtmlParser.fs @ line 710

`            | Tag(_, "br", []) :: rest ->
                let t = HtmlText Environment.NewLine
                parse' docType (t :: elements) expectedTagEnd parentTagName rest`

If I understand the br element is being replaced with a newline.

Does this mean that it is not possible to us FSharp.Data.HtmlDocument.New on a subset of HtmlNodes and retain the mean of br?

for the attached html sample the goal is to extract the interestingContent div and use it to create a new Html document with the br elements retained.

Thanks
[sample.txt](https://github.com/fsharp/FSharp.Data/files/1127399/sample.txt)

**Comment by realvictorprm** [comment]
noticed but not looked into it yet.

**Comment by Regent** [comment]
Shouldn't `br` be producing DOM node? E.g.
```xml
<br><br>
```
Parsed into
```fsharp
HtmlDocument.New [
    HtmlNode.NewElement("br")
    HtmlNode.NewElement("br") ]
```

**Comment by ovatsus** [comment]
By design br's are translated into a newline and all html entities is resolve, to make it easier to use. When creating elements, the opposite should also happen
