### ISSUE TITLE
Long term: Simplifying to just .NET Standard 2.0?

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Data#1060]
This is a long term thing about how we're simplifying type providers.  There's no immediate action required

We've completed the work in the F# compiler and compiler service to [support ".NET Standard 2.0" libraries and type providers](https://github.com/Microsoft/visualfsharp/pull/3307).  These improvements will gradually be rolled out into compilers and editors (that will take a while, as you can imagine). I tested this work primarily with FSharp.Data.

Once this becomes widely available I believe we will be able to move to a world where FSharp.Data has only two DLLs in its nuget package, like this:
```
    lib/netstandard2.0/FSharp.Data.dll
    lib/netstandard2.0/FSharp.Data.DesignTime.dll
```
I've checked and **all** of FSharp.Data compiles and passes tests when compiled as a .NET Standard 2.0 library.  No ``#if`` are needed.  [The branch I did this in is here](https://github.com/fsharp/FSharp.Data/compare/master...dsyme:ns2?expand=1), and it includes the work to convert to .NET SDK 2.0 project files if you want to take a look at how to do this, e.g. for [FSharp.Data.DesignTime.fsproj](https://github.com/fsharp/FSharp.Data/compare/master...dsyme:ns2?expand=1#diff-c64e6937c9d61836ece07888b82ad1a8) (this branch assumes an install of .NET SDK 2.0 preview2 or after, and consuming it requires the fixes in the F# compiler linked above)

Note that .NET Standard 2.0 libraries are supported by Mono 5.0 and .NET 4.6.1 and above, and .NET Core App 2.0 and above.   If we wanted to continue to be able to reach earlier runtimes profiles with new versions of FSharp.Data then we could also add a netstandard1.6 runtime DLL.  The designtime DLL should continue to be netstandard2.0.  If not, people who want to target those platforms can just use existing versions of the FSHarp.Data package

**Comment by ovatsus** [comment]
If we do that will it keep working for people still in VS2015 and F# 3.1?

**Comment by buvinghausen** [comment]
Great stuff Don! Looking forward to v3 making it out to nuget.

**Comment by 7sharp9** [comment]
@dsyme So for consumes from the mobile side, they would have to consume netstandard2.0 in the future?

**Comment by 7sharp9** [comment]
Is zlib available as netstandard for this?

**Comment by dsyme** [comment]
@7sharp9 Re mobile Xamarin will support .NET Standard 2.0

@ovatsus If we go ahead with this, I assume VS2015 users would be stuck with the latest available package specifically targeting .NET 4.x

However, I think it is a while before the F# compiler toolchains will support .NET Standard 2.0 type providers - the proposal in the linked bugs/PRs was rejected because it involves shipping a mere 96 extra tiny facade-like DLLs as part of any deployment of the F# compiler (or any tool based on FSharp.Compiler.Service that would have to load such a type provider dynamically).  This approach was confirmed by @terrajobst but was deemed 'too much' by those deploying F# compiler components, e.g. Visual F#, and I can understand why. There are probably workarounds but they are non-trivial and we shouldn't rely on them for FSharp.Data

So there is not going to be any change soon, though I'm glad to have done the prototype to have worked out what some of the issues are

@7sharp9 Re zlib - My understanding from [this branch](https://github.com/fsharp/FSharp.Data/compare/master...dsyme:ns2?expand=1) is that the necessary compression algos are included in .NET Standard 2.0

**Comment by 7sharp9** [comment]
@dsyme I was specifically looking at this reference:
https://github.com/dsyme/FSharp.Data/blob/ee4f12e275e77fcaa13990be2602aa75398955bd/src/Net/Http.fs#L651

There is a net standard version of that lib available from a different nuget: 
https://www.nuget.org/packages/Iconic.Zlib.Netstandard/

Im using FSharp.Data where I don't actually use any TP's Im only using json helpers etc.

**Comment by 7sharp9** [comment]
What Im doing, I only use the json helpers, is use packet to add the needed files and the relevant defines:

```
File:UriUtils.fs
File:Http.fs
File:IO.fs
File:Caching.fs
File:TextConversions.fs
File:TextRuntime.fs
File:Pluralizer.fs
File:NameUtils.fs
File:StructuralTypes.fs
File:StructuralInference.fs
File:JsonValue.fs
File:JsonConversions.fs
File:JsonExtensions.fs
File:JsonRuntime.fs
```

```
    <DefineConstants>$(DefineConstants);FX_NO_LOCAL_FILESYSTEM</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_CUSTOMTYPEDESCRIPTOR</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_REGEX_COMPILATION</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_URI_WORKAROUND</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_REFERER</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_HOST</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_AUTOMATICDECOMPRESSION</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_CONTENTLENGTH</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_USERAGENT</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_CONNECTION</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_DATE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_EXPECT</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_IFMODIFIEDSINCE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_RANGE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBREQUEST_TIMEOUT</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBRESPONSE_CHARACTERSET</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_ENVIRONMENT_VARIABLES</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_GETENCODING_BY_CODEPAGE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBRESPONSE_IS_FROM_CACHE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBRESPONSE_IS_MUTUALLY_AUTHENTICATED</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NO_WEBRESPONSE_CLOSE</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_HAS_WEBRESPONSE_SUPPORTS_HEADERS</DefineConstants>
    <DefineConstants>$(DefineConstants);FX_NET_CORE_REFLECTION</DefineConstants>
```
It would be nice to have a nuget for this thats usable from .NET "standard" 2.0

**Comment by mike-morr** [comment]
@dsyme Any update on the status of getting the type providers working on .NET Standard 2.0?

**Comment by quintusm** [comment]
It would really be nice if we could get a .Net Standard 2.0 version out there....

**Comment by JamesHealey94** [comment]
Related: https://github.com/fsharp/FSharp.Data/pull/1118

**Comment by buvinghausen** [comment]
@quintusm 3.0 beta was posted last week...

**Comment by quintusm** [comment]
Thanks I have already started using it and it seems to work fine 👍
