### ISSUE TITLE
Why does this code crash when executed a second time in FSI?

### ISSUE THREAD

**Issue by Soldalma** [fsharp/FSharp.Data#1062]
I left the comment below on StackOverflow and two prominent contributors, rmunn and Fyodor Soikin, suggested I report it as a bug.

I have some code that generates an exception the second time  it is executed in FSI.

The sequence is the following:  

1) Select all lines above it, run on FSI using Alt+Enter.  

2) Select the code, run on FSI using Alt+Enter. So far no errors.  

3) Run the selected code again by hitting Alt+Enter. Error (see below).  

Here are the lines of code generating this behavior: 

let assetsMap  =
    assetInfo.Rows
    |> Seq.filter (fun (rw: AssetsInfo.Row) -> Set.contains rw.Ticker assetsTickerSet)
    |> List.ofSeq
    > List.map (fun rw -> rw.Ticker, Asset.constructor rw) // Frame.ReadCSV called here
    |> Map.ofSeq  Relevant info:  type AssetsInfo = FSharp.Data.CsvProvider<...>   

Error message: 

System.InvalidOperationException: tried to skip The input sequence has an insufficient number of elements. 1 past the end of the seq    at Microsoft.FSharp.Collections.SeqModule.Skip@1316.GenerateNext(IEnumerable`1& next)    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()    at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@176.GenerateNext(IEnumerable`1& next) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 176    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()    at Microsoft.FSharp.Collections.Internal.IEnumerator.next@187[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)    at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@182.System-Collections-IEnumerator-MoveNext()    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)    at <StartupCode$FSI_0035>.$FSI_0035.main@() in H:\Dropbox\BitBucket\VSProjects\Fractal10\Fractal10\Program.fs:line 139 Stopped due to error
-- | --

**Comment by ovatsus** [comment]
Tested similar code on a csv file and I couldn't repro. Please reopen if you have a full snippet that reproduces the problem that we can try

**Comment by himekami** [comment]
Hi,
I can confirm this issue still persists. 
I'm having exactly the same issue as above when i ran the following code the second time.
First time OK.

This is my code:

`#r "nuget: FSharp.Data"
open FSharp.Data

[<Literal>]
let file = """/home/azmi/all.csv"""

type Txn = CsvProvider<file, CacheRows=false>
let rows = Txn.Load(file).Rows

rows
|> Seq.filter(fun r -> r.code.StartsWith("Google"))
|> Seq.countBy(fun r -> r.code)
|> Seq.iter (printfn "%A")
`
