### ISSUE TITLE
HTML sample references decommissioned site

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Data#1064]
the docs here:

https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/HtmlProvider.fsx

reference https://www.bmreports.com/servletcom.logica.neta.bwp_MarketDepthServlet which has been [decommissioned](https://www.elexon.co.uk/change/new-balancing-mechanism-reporting-service-bmrs/)

The code below would be an adequate replacement, though the reference HTML data used for type checking should be downloaded and used as schema
```

type MarketDepth = HtmlProvider<"https://www.bmreports.com/bmrs/?q=balancing/systemsellbuyprices">

let mrktDepthData = MarketDepth.GetSample()

let mrktDepthTable = mrktDepthData.Tables.MyTable1

//for row in mrktDepthTable.Rows do 
//   row.

// Look at the most recent row. Note the 'Date' property
// is of type 'DateTime' and 'Open' has a type 'decimal'
let firstRow = mrktDepthTable.Rows.[0]
let settlementDate = firstRow.``Settlement Date``
let acceptedBid = firstRow.ABV
let acceptedOffer = firstRow.ASV

// Print the bid / offer volumes for each row
for row in mrktDepthTable.Rows do
  printfn "Bid/Offer: (%A, %A, %A)" row.``Settlement Date`` row.ABV row.ASV
```

**Comment by ovatsus** [comment]
@colinbull , you change the example to be about F1 instead, but there was a bit of leftovers: https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/HtmlProvider.fsx#L21

Can you clean it up?

**Comment by ovatsus** [comment]
This was already done
