### ISSUE TITLE
Type for 0.00 value not inferred correctly

### ISSUE THREAD

**Issue by BenHewins** [fsharp/FSharp.Data#1065]
Hi,

When a sample is provided to the JsonProvider which has a value like 0.00, it currently defaults to generating an int. If you then try and parse json where that field is set to a decimal value it will be silently truncated:

```fsharp
> type Location = JsonProvider<"""{ "x" : 0.500, "y" : 0.000 }""">;;
type Location = JsonProvider<...>
> let a = Location.Parse """{ "x" : -0.250, "y" : 0.800 }""";;
val a : JsonProvider<...>.Root = {
  "x": -0.250,
  "y": 0.800
}
> a.Y;;
val it : int = 0
```

This is also understandable behaviour, although I think that at least an option to warn/error on truncated values when parsing would be valuable. 

The combination of these two behaviours creates examples like the above, which are reasonable but very easy to trip up on when the json is more complex than a couple of fields. At the moment this is easy enough to deal with by changing the values in the sample, but I think that the experience could be improved. Personally I think that erroring when trying to parse a decimal as an int would be a good solution but I may be missing something (other than it being a breaking change).

**Comment by ovatsus** [comment]
Yes, it should give a runtime error

**Comment by ovatsus** [comment]
Making the 0.000 not be inferred as an integer is actually quite hard to fix. We parse the json, and actually get a 0.000 decimal. However, when we get to the inference part, we lost the string, so we don't know if this came from "0" or "0.0000". We would have to carry the original string around to the inference part to make that decision
