### ISSUE TITLE
Uninformative error when building a project

### ISSUE THREAD

**Issue by souserge** [fsharp/FSharp.Data#1066]
I am trying to build a test project with FSharp.Data package installed, but unfortunately an error appears:
`C:\Program Files\dotnet\sdk\2.0.0\FSharp\Microsoft.FSharp.Targets(224,9): error MSB6006: "RunFsc.cmd" exited with code -1073741571. [C:\FsProject\FsProject.fsproj]`

**Comment by dsyme** [comment]
See https://github.com/Microsoft/visualfsharp/issues/3303 for workaround

**Comment by souserge** [comment]
@dsyme thank you.
