### ISSUE TITLE
Reenable documentation tests

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#1075]
All the documentation tests were failing with The module/namespace 'System.Runtime.CompilerServices' from compilation unit 'mscorlib' did not contain the namespace, module or type 'ExtensionAttribute', so right now they have the Ignore attribute

**Comment by tpetricek** [comment]
They were always fairly flaky... not entirely sure what would be causing this. Sounds like some sort of binding-redirect-kind-of-thing but no idea how exactly this is misbehaving.

**Comment by ovatsus** [comment]
I hoped that #1085 fixed it, but it didn't. @dsyme , any idea?

The weird thing is that executing DocumentationTests.fs on FSI actually works, the bogus error about ExtensionAttribute is gone, and instead we just get the valid errors about #1086, #1087, and #1088

**Comment by ovatsus** [comment]
This seems to have been fixed by #1094
