### ISSUE TITLE
[CSV Type provider] cannot parse CSV with double quotes inside

### ISSUE THREAD

**Issue by dnauck** [fsharp/FSharp.Data#1076]
Hi,

i've the following issue with the CSV Type Provider:

As soon as there is a odd number of double quotes in a csv file the CSV type provider skips (combines) rows.

The expected result are 3 rows with 3 columns.

CSV Test File:

    Release;ANW-ID;Kurzbeschreibung
    17.0;0001A;Anwendung "1
    17.0;0002B;Anwendung "2" 
    17.0;0003C;Anwendung 3

**Comment by realvictorprm** [comment]
I don't know the source code exactly but as ambiguous as the specification of csv is I guess its only possible to tell the provider to not interpret quotes (as option).

**Comment by ovatsus** [comment]
There is already a parameter for it, see here - http://fsharp.github.io/FSharp.Data/reference/fsharp-data-csvprovider.html - you will need to set the Quote parameter to some other character so the quotes can be considered part of the text

**Comment by dnauck** [comment]
Yes, used a uncommon char as Quote parameter and now it works. Thanks.
