### ISSUE TITLE
Version 2.4 breaks FSharp.Data.Http.*Request and requests are immediately aborted.

### ISSUE THREAD

**Issue by f4hy** [fsharp/FSharp.Data#1077]
Upgrading to 2.4 broke our codebase everywhere that we used Http.Request or Http.AsyncRequest where the requests would abort immediately and the apache logs indicated the calls were timing out but they would return seemingly instantly.

`WebException message The request was aborted: The request was canceled.
webexception:System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.`

Not sure if the default timeout was set to something very small and somehow the `timeout` parameter on Http.Request is not working, or if some other issues is causing the requests to be immediately aborted.

Downgrading to 2.3.3 resolved the problem.

**Comment by f4hy** [comment]
@ovatsus  is it related to commit `602f29a9cbaaac22bccc614cf23e409a73111956` ?

**Comment by ovatsus** [comment]
@baronfel, can you have a look at this? It seems we're disposing a stream when we shouldn't

@f4hy, can you share a small snippet of code that repro's the issue?

**Comment by baronfel** [comment]
@ovastus I'll dig into it. 
@f4hy a snippet would help me zero in quickly!

**Comment by f4hy** [comment]
So in writing a script to reproduce the issue, I found it has to do with the length of the input body test. If it is small, it works fine, if it is over a certain size the request immediately fails.

```
#r @"FSharp.Data.dll"
open FSharp.Data

let bodyString = seq {for i in 0..1000 -> "x\n"} |> String.concat ""
let body = FSharp.Data.FormValues([("input",bodyString)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body)
//Works fine

let bodyString2 = seq {for i in 0..2000 -> "x\n"} |> String.concat ""
let body2 = FSharp.Data.FormValues([("input",bodyString2)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body2)
//Immediately throws System.Net.WebException
```

http://httpbin.org/post is just some public url I found so we can test this and not test against my production result.

So the fact that this fails just when the body is a certain size seems odd, something is overflowing? This doesn't crash when running on 2.3.3 but does fail on 2.4

**Comment by baronfel** [comment]
It sounds like there may be a bug in the asyncRead or asyncCopy functions,
which takes 4k at a time. Let me add some tests around your examples to
validate.

**Comment by baronfel** [comment]
I've replicated the problem using your example and added it as a test case in the repo. Working on a resolution now.

**Comment by baronfel** [comment]
I have fixed your issue, PR incoming!

**Comment by ovatsus** [comment]
Released 2.4.1 with the fix

**Comment by legomind** [comment]
I am still running into this issue.
Any ideas why?

**Comment by ovatsus** [comment]
@baronfel, can you have a look?

**Comment by baronfel** [comment]
I see the problem. There's a bug in my `CombinedStream` implementation that sometimes asks a stream to read past where its buffer contains.  I'll send a PR momentarily.
