### ISSUE TITLE
HtmlDocument cannot parse document with some JavaScript RegEx replace code

### ISSUE THREAD

**Issue by eugbaranov** [fsharp/FSharp.Data#1091]
Having regex replace in JavaScript for left angle bracket results in the parser not being able to parse HTML.
Consider the following HTML:
```html
<head>
    <script>
        "".replace(/</g, "")
    </script>
</head>
<body>
</body>
```
The following will throw an exception:
```fsharp
let test = html |> HtmlDocument.Parse
test.Body()
```

**Comment by ovatsus** [comment]
Do you want to try and send a PR to fix it?

**Comment by Regent** [comment]
I'll give it a try.

**Comment by colinbull** [comment]
10 months on, but I think I have a fix here. @eugbaranov can you check? The original failing test now passes, and only one of the other signature files required a regen.

**Comment by eugbaranov** [comment]
`HtmlParser` changes looks good to me.
