### ISSUE TITLE
HtmlDocument.Parse() fails to read correctly unquoted attribute (e.g. href)

### ISSUE THREAD

**Issue by ivoh** [fsharp/FSharp.Data#1101]
Parsing of HTML document with Anchor tags that have href attribute with not quoted value (e.g. `<a href=http://aaa-bbb-ccc/AAAAA/something.htm>`  this is still valid html) mixes up the attribute name and value.
The serialized value is presented as `<a hrefaaa-bbb-cccaaaaasomething.htm="http:">`

FSharp.Data v. 2.4.2.0
File [failingpage.htm]:
```
<html>
<body>
<a href=http://aaa-bbb-ccc/AAAAA/something.htm>Click Here</a>
</body>
</html>
```

**Repro:**

```
open FSharp.Data
open System.IO

let content = File.ReadAllText("./failingpage.htm")
let html = HtmlDocument.Parse(content)
```

**Actual behavior**
FSI shows:
```
val content : string =
"<html>
<body>
<a href=http://aaa-bbb-ccc/AAAAA/"+[52 chars]
val html : HtmlDocument =
<html>
<body>
<a hrefaaa-bbb-cccaaaaasomething.htm="http:">Click Here</a>
</body>
</html>
```

this is true
`html.CssSelect("a").[0].Attribute("hrefaaa-bbb-cccaaaaasomething.htm").Value() = "http:"`

this fails as there is no attribute href
`html.CssSelect("a").[0].Attribute("href")`

**Expected behavior** would be Content of file [failingpage.htm]
```
<html>
<body>
<a href=http://aaa-bbb-ccc/AAAAA/something.htm>Click Here</a>
</body>
</html>
```

And this should be true
`html.CssSelect("a").[0].Attribute("href").Value() = "http://aaa-bbb-ccc/AAAAA/something.htm"`

**Comment by ovatsus** [comment]
@Regent, want to try fixing this since you're already familiar with this part of the code?
