### ISSUE TITLE
[Packaging] Provide Nuget package(s) with just the parsing/helpers

### ISSUE THREAD

**Issue by baronfel** [fsharp/FSharp.Data#1116]
I've seen comments echoed in a few places that in lieu of being able to use the full providers on netcore and such that it would be useful to be able to just reference the parsing and utility methods. While it is possible now to Paket-file-include the relevant files, it might be nice to provide those in a nuget package that could be referenced individually as well.

Relevant questions:

- What frameworks? Are we at a point where we can just target netstandard2.0 and expect new users to default to that?
- Can the provider Nugets be made dependent on these new Nugets, or should they use the existing embedding?
- How should any new packages be organized? 
  * FSharp.Data.Csv: with CsvFile and CsvReader?
  * FSharp.Data.Net (or HTTP?): with UriUtils and Http?
  * FSharp.Data.Json: JsonValue/JsonParser/JsonExtensions?
  * FSharp.Data.Html: HtmlCharRefs/HtmlParser/HtmlOperations/HtmlCssSelectors/HtmlTypes from HtmlRuntime.fs?

**Comment by ovatsus** [comment]
Instead of splitting into multiple packages maybe we could just have the netstandard2.0 target not include the TP code and just the rest? I'm not a fan of overly componetizing stuff, everything just gets more complicated for the common case (think all the fsx scripts that now need to reference multiple dlls)

**Comment by baronfel** [comment]
So wrap all the Runtime components in an offer, essentially? That could work too!

**Comment by ovatsus** [comment]
Well, FSharp.Data.dll is already only the runtime components, except for an attribute saying to look at FSharp.Data.Designtime.dll for the type providers. So ideally if TPs don't work in dotnet core, the attribute should just be ignored and no change be needed...

On 29 Dec 2017 18:54, Chet Husk <notifications@github.com> wrote:

So wrap all the Runtime components in an offer, essentially? That could work too!

**Comment by eulerfx** [comment]
This is somewhat related to the issue we raised a while back #647. Creating a .netstandard 2 target would solve #647 for .netstandard code, but the issues would remain for .net classic. 

Like the OP, I'm slightly in favor of having, say FSharp.Data.Json, referenced from here, but I understand upgrade pain and having to update a bunch of fsx files.

Summary of options (that I'm aware of):

1. Target .NET Standard, excluding TPs. This would address the TP issue in #647 for .NET Standard, but the issue would remain for .NET Classic.
2. Create an FSharp.Data.NoTP package that excludes the TP attribute. This can be done in addition to 1. Users wanting to avoid TPs can reference this new package and it doesn't break existing users.
3. Create separate, packages, ie FSharp.Data.Json which don't have TPs. This has the downside of causing upgrade pains for folks using fsx scripts. But it would be great to have a standalone FSharp.Data.Json. At Jet, we'd use that exclusively and would OSS our internalized version of FSharp.Data along with all the extensions we've built around it. 
4. Do something with paket which causes FSharp.Data.DesignTime.dll to be copied into bin directory.  I don't think this would address the .NET Standard issue? @baronfel you mentioned doing something with paket include - what exactly would it be?

**Comment by baronfel** [comment]
@eulerfx what I'm meaning with `paket include` is paket's ability to pull in specific revisions of specific files in a git or github repository.  Docs are [here](https://fsprojects.github.io/Paket/github-dependencies.html#Referencing-a-single-file) for this functionality, but the short version is that paket will add a lockfile entry for the files in question, download them to `paket-files/{repoName}/{path/to/file}`, and optionally add the link to your project file. This ability could be used right now to pin specific versions of particular modules/files if you needed them.

You can see an example [paket.dependencies](https://github.com/fsharp/FSharp.Data/blob/master/paket.dependencies) in this repo, along with the [paket.lock](https://github.com/fsharp/FSharp.Data/blob/master/paket.lock#L534)

**Comment by ovatsus** [comment]
.net core is not supported, so this is no longer a problem, right?
