### ISSUE TITLE
JSON Provider optional Json value on root level

### ISSUE THREAD

**Issue by Thorium** [fsharp/FSharp.Data#1121]
I'm trying to parse JSON and I'm not in control of schema. ( https://ideal-postcodes.co.uk/ )
The problem is that the schema is a JSON object and not an array.

An code example how I load it:

```fsharp
type AddressData = JsonProvider<"""{
    "result": [{
        "postcode": "ID1 1QD",
        "post_town": "LONDON",
        "line_1": "2 Barons Court Road",
        "country": "England",
    },{
        "postcode": "ID1 1QD",
        "post_town": "LONDON",
        "building_name": "",
        "organisation_name": "ID Consulting Limited",
        "line_1": "ID Consulting Limited",
        "country": "England",
    }],
    "code": "2000",
    "message": "Success"
}""">

let r = AddressData.AsyncLoad(
                "https://api.ideal-postcodes.co.uk/v1/postcodes/" + postcode + "&api_key=" + apiKey
            )
```

Sadly there might be cases when the "result" is not gotten at all: `{"code":4040,"message":"Postcode Not Found"}`. What happens is my AsyncLoad throws a parsing exception. If I set the root as an array, then I also get an AsyncLoad parsing expression because the JSON returned from the service is not starting with an array.

I tried to search the documentation but didn't found how to set items as optional in JSON.

I think the documentation should clearly describe that JSONProvider can be used only with services that return JSON arrays on root level.

**Comment by ovatsus** [comment]
It is supposed to work when the root element is an object as well, I think there are even test cases for that, this is probably a bug in the structure inference

**Comment by ovatsus** [comment]
Ah, wait, on a second look I see the problem. You need to add a second example where the result field is missing, otherwise there is no way for the structure inference to know it's optional

**Comment by Thorium** [comment]
How can I add "a second example" to root level?

**Comment by ovatsus** [comment]
You can change the sample to be a Json array of examples and then there's a SampleIsList parameter (or something similar, can't remember the name right now, check the docs) that says to the TP to not infer the list but instead the structure of the elements of the list

On 24 Jan 2018 10:44, Tuomas Hietanen <notifications@github.com> wrote:

How can I add "a second example" to root level?

**Comment by Thorium** [comment]
Thanks, working!

**Comment by ovatsus** [comment]
Maybe try and update the documentation to make this more obvious?

On 24 Jan 2018 11:56, Tuomas Hietanen <notifications@github.com> wrote:

Thanks, working!
