### ISSUE TITLE
F# error with WorldBankData Indicators

### ISSUE THREAD

**Issue by Xieyanliang** [fsharp/FSharp.Data#1145]
1 #I @"..\packages" 
2 #r @"FSharp.Data.2.4.6\lib\net45\FSharp.Data.dll" 
3 open FSharp.Data 
4 let wb = WorldBankData.GetDataContext () 
5 let countries = wb.Countries 
6 let pop2000 = [ for c in countries -> c.Indicators.Population, total.[2000]]

World.fsx(6,39): error FS3021: 在所提供类型“FSharp.Data.WorldBankData+ServiceTypes+Indicators”成员“GetMethods”中发生意外异常: 类型提供程序“ProviderImplementation.WorldBankProvider”报告了错误: Invalid JSON starting at character 290164, snippet =
"id":"10",
json =
[{"page":12,"pages":18,"perpage":"1000","total":17066},[{"id":"persicp.adqq2preTtot","name":"Adequacy of benefits in 2nd quintile (%) - Contributory Pensions (preT)","source":{"id":"29","value":"The Atlas of Social Protection: Indicators of Resilience and Equity"},"sourceNote":"","sourceOrganization":"The Atlas of Social Protection: Indicators of Resilience and Equity (ASPIRE)","topics":[]},{"id":"persicp.adqq1urb","name":"Adequacy of benefits in poorest quintile (%) - Contributory Pensions -urban","source":{"id":"29","value":"The Atlas of Social Protection: Indicators of Resilience and Equity"},"sourceNote":"","sourceOrganization":"The Atlas of Social Protection: Indicators of Resilience and Equity (ASPIRE)","topics":[]},{"id":"persicp.adqq1tot","name":"Adequacy of benefits in poorest quintile (%) - Contributory Pensions ","source":{"id":"29","value":"The Atlas of Social Protection: Indicators of Resilience and Equity"},"sourceNote":"","sourceOrganization":"The Atlas of

**Comment by ovatsus** [comment]
Can you try in 3.0-beta?

I just tried this and it worked fine:

    let wb = WorldBankData.GetDataContext()
    let countries = wb.Countries
    let pop2000 = [ for c in countries -> c.Indicators.``Population, total``.[2000]]

**Comment by Xieyanliang** [comment]
What is 3.0-beta? Can you explain in detail ? Thank you very much.

**Comment by ovatsus** [comment]
https://www.nuget.org/packages/FSharp.Data/3.0.0-beta

You have to change your nuget client options to allow prerelease versions to get it

**Comment by Xieyanliang** [comment]
I updated my win7 to win10, no error now.
