### ISSUE TITLE
Problem with loading the scheme from xsd files

### ISSUE THREAD

**Issue by Etschbeijer** [fsharp/FSharp.Data#1161]
Hi,
I started working with xml files before a short time and was using  FSharp.ata with out FSharp.data.xsd and I had no problem, when I tried to pick specific elements form the file.
But the used scheme is queite complex and I hoped to avoid rewriting it in an xml file because a xsd file is available.
When i used the FSharp.data.xsd everything seemd to work properly because the whole file was loaded as normal but when I tried to pick a specific element the array was always empty or not existing.

Shall I give you the example file an scheme file and a shortage of the code?

Thank you for your help beforehand.

**Comment by giacomociti** [comment]
Yes, please add the xsd and code

**Comment by Etschbeijer** [comment]
I have the problem with the FSharp.Data.Xsd and so I report my problem there. Thank you for the fast respond.

**Comment by giacomociti** [comment]
we can close this, the xml was invalid due to a namespace mismatch
