### ISSUE TITLE
Question: Is there any reason there is no module with standard HTTP status codes?

### ISSUE THREAD

**Issue by NatElkins** [fsharp/FSharp.Data#1163]
When using the HTTP utilities, I noticed that there were constants for common headers, but not status codes.  Would that be a welcome PR?  I would create the status code constants as per https://en.wikipedia.org/wiki/List_of_HTTP_status_codes .

**Comment by ovatsus** [comment]
Yes, that would be a nice addition

**Comment by 0x456464** [comment]
I'll take a look at this now.

**Comment by 0x456464** [comment]
Submitted a pull request.

**Comment by ovatsus** [comment]
Seems you both sent PRs to do the same
