### ISSUE TITLE
Fsharp. Data loads Fsharp.Core v4.3.1.0

### ISSUE THREAD

**Issue by anakreontas** [fsharp/FSharp.Data#1169]
I am using the library in a project compiled with Fsharp.Core 4.0.0.1. The project compiles but raises errors at run time because it fails to load Fsharp.Core 4.3.1.0. The library seems to request that version. In the nuspec file the library requests version 4.0.0.1 but the IL code from fsharp.data.dll contains the following :
.assembly extern Fsharp.Core 
{
.publickeytoken =... 
.ver 4:3:1:0
}

This is the case for Fsharp.Data version 2:4:6:0. Please advice how to make the library request fsharp.core 4.0.0.1.

**Comment by ovatsus** [comment]
Since 2.4.6, the minimum supported FSharp.Core is 4.3.1.0. The only workaround is to stay in version 2.3.3 forever
