### ISSUE TITLE
CsvProvider error when referencing netstandard2.0\FSharp.Data.dll, but not with net45\FSharp.Data.dll

### ISSUE THREAD

**Issue by jonsagara** [fsharp/FSharp.Data#1176]
Hello,

I'm trying to use `CsvProvider` in an `.fsx` file, but I'm getting the following error:

> Error FS1109 A reference to the type 'FSharp.Data.CsvProvider,Sample="C:\\Dev\\SANDBOX\\FSharpGetProgrammingBookSource\\data\\FootballResults.csv"' in assembly 'FSharp.Data' was found, but the type could not be found in that assembly FSharpTypeProvider

The script executes and gives the correct results, but the error is always present in the editor and in the Error List, and I don't have intellisense.

Here is the script:

```
#I @"C:\Users\Jon\.nuget\packages\"
#r @"FSharp.Data\3.0.0-beta3\lib\netstandard2.0\FSharp.Data.dll"
//#r @"FSharp.Data\2.4.6\lib\net45\FSharp.Data.dll"

open FSharp.Data

type Football = CsvProvider< @"C:\Dev\SANDBOX\FSharpGetProgrammingBookSource\data\FootballResults.csv" >
let data = Football.GetSample().Rows |> Seq.toArray
```

If I comment out the `netstandard2.0` version of `FSharp.Data.dll` and instead reference the `net45` version, then the error goes away completely, and I once again have intellisense:

```
#I @"C:\Users\Jon\.nuget\packages\"
//#r @"FSharp.Data\3.0.0-beta3\lib\netstandard2.0\FSharp.Data.dll"
#r @"FSharp.Data\2.4.6\lib\net45\FSharp.Data.dll"

open FSharp.Data

type Football = CsvProvider< @"C:\Dev\SANDBOX\FSharpGetProgrammingBookSource\data\FootballResults.csv" >
let data = Football.GetSample().Rows |> Seq.toArray
```

Any ideas about what's happening? Any known workarounds?

Version information:
* Windows 10 
* VS 2017, 15.7.4
* Microsoft (R) F# Interactive version 10.1.0 for F# 4.1
* The `.fsx` file is in an F# .NET Core 2.1 console app project, if that matters
* .NET Core SDK 2.1.301

Thank you,

Jon

**Comment by nhirschey** [comment]
It's not just you, I ran into the same thing. I went back to net46 but there seem to be workarounds. See this and related issues: https://github.com/ionide/ionide-vscode-fsharp/issues/839

**Comment by dsyme** [comment]
This isn't a bug in FSharp.Data. You likely need

    #r "netstandard"

See https://github.com/ionide/ionide-vscode-fsharp/issues/839#issuecomment-395054266 also

**Comment by jonsagara** [comment]
@ovatsus That would be tremendously helpful for people new to F# (like me). Thanks!

**Comment by OnurGumus** [comment]
I am still having this issue with Visual Studio Code. The .fsx file runs fine but the vscode complains about it.
Here's my sample code : 
```
#r @"C:\Users\Onur.Gumus\.nuget\packages\fsharp.data\3.0.0\lib\netstandard2.0\FSharp.Data.dll"
#r @"C:\Users\Onur.Gumus\.nuget\packages\fsharp.data\3.0.0\lib\netstandard2.0\FSharp.Data.DesignTime.dll"
#r  "netstandard"
open FSharp.Data
[<Literal>]
let path = "d:\\PassengerList.csv"
let url = "http://google.com"

let sendRequest url body =
     Http.AsyncRequestString(
        url, headers = [HttpRequestHeaders.ContentType HttpContentTypes.Json], body = TextRequest body)

type Passengers = CsvProvider<path>
```
And relevant screenshot:
![image](https://user-images.githubusercontent.com/4114592/51847407-168ba480-2335-11e9-88fe-9f189d87da00.png)

**Comment by voronoipotato** [comment]
It appears this issue is not closed for ionide.

**Comment by davidspiess** [comment]
Also having this issue. Only way to fix it, is referencing **net45**.

**netstandard2.0 error**

![image](https://user-images.githubusercontent.com/992674/90393323-c9932e80-e090-11ea-9e4c-66dd1acefd8b.png)

**net45 works fine**

![image](https://user-images.githubusercontent.com/992674/90393369-e2034900-e090-11ea-8555-8d8d7e57c470.png)

I get the same error in VSCode and Visual Studio

**Comment by nhirschey** [comment]
Hi David, what platform are you on?

I’m on Windows. I’ll occasionally get errors like this trying to use dotnet core via ionide. The screenshots look like ionide. 

 However, if you use visual studio you’ll be on .net and netstandard2.0 should work for you (I’m using the latest community preview versions).  It’ll also work on my current incantation of ionide, but the reliability of that for me is fragile.

**Comment by nhirschey** [comment]
For reference, see below (the ionide intellisense errors are what they are, but this shows that FSharp.Data works on dotnet core and netstandard2.0 for your query). I'm including dotnet info below for reference too:

![image](https://user-images.githubusercontent.com/5226115/90413842-a490c280-e074-11ea-902b-4c66c4235cc1.png)


.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

**Comment by davidspiess** [comment]
@nhirschey thanks for your effort! You are right, if executed it works as expected, so this is basically a Ionide intellisense bug and not related to `FSharp.Data`.
