### ISSUE TITLE
FSI MissingMethodException 

### ISSUE THREAD

**Issue by IvanAntipov** [fsharp/FSharp.Data#1177]
If I use FSharp.Data.Http.RequestString directly from FSharp interactive it works fine

If I build a module that use FSharp.Data, System.MissingMethodException occured.

```
// Program.fs
open System
open FSharp.Data

module X =
    let req (url : string) =
        FSharp.Data.Http.RequestString(url)

[<EntryPoint>]
let main argv =
    X.req "https://fsharp.org" |> ignore
    printfn "Hello World from F#!1"
    0 // return an integer exit code
```

```
//Script.fsx
#r @"lib\FSharp.Data.DesignTime.dll"
#r @"lib\FSharp.Data.dll"
#r @"bin\Debug\net471\FSharpDataBuild.exe"

open Program.X

//FSharp.Data.Http.RequestString("https://fsharp.org") // Request directly - OK
req "https://fsharp.org" // Request throughout assemly // System.MissingMethodException
```

Repro:
[FSharpDataBuild.zip](https://github.com/fsharp/FSharp.Data/files/2148861/FSharpDataBuild.zip)
 
UPD: after I restarted VS Code, and changed fsi path from "c:\Program Files (x86)\Microsoft SDKs\F#\4.1" to  "c:\Program Files (x86)\Microsoft SDKs\F#\10.1" problem has gone on repro, but still actual on prod. I try to create new repro.
UPD: I found a workaround for prod. I removed FSharp.Core.dll from ./bin directory, where others .dll are located, and Exception has gone, but I did't managed to create a repro

**Comment by dsyme** [comment]
This does look like a problem in Ionide not FSHarp.Data

**Comment by dsyme** [comment]
I tried on Windows and it works fine, I think we should close this
