### ISSUE TITLE
XSD date handling

### ISSUE THREAD

**Issue by giacomociti** [fsharp/FSharp.Data#1181]
I'd like to discuss [this issue](https://github.com/fsprojects/FSharp.Data.Xsd/issues/24) here, now that XSD support is merged. I feel uneasy ignoring it; we know that type providers are more geared towards reading than writing, but providing a ctor with a `System.DateTime` parameter that leads to creating invalid xml is simply wrong.

I see two alternatives: the easy one is to drop support for `xs:date`, falling back to `string`; another option may be to rely on #980 (once it gets merged), mapping `xs:dateTime` to `DateTimeOffset` and `xs:date` to `DateTime` and, [when formatting xml dates](https://github.com/fsharp/FSharp.Data/pull/980/files#diff-0c8d16397cad995a7e34291cefb11b22R211), use the proper format (including time for `DateTimeOffset`  and excluding it for `DateTime`). This is a bit hacky, but would solve the issue with no impact on the other (non-XML) type providers.

**Comment by ovatsus** [comment]
I think relying on #980 would make sense. I want to merge that one and #1027 next

**Comment by ovatsus** [comment]
@giacomociti , #980 is merged, can you update the XSD support to take advantage of it?
