### ISSUE TITLE
question: 3.0 release?

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Data#1182]
Hi @ovatsus,

Any idea when 3.0.0 will come out of pre-release?  I'd like to update FsLab to have .NET SDK and .NET standard support, see https://github.com/fslaborg/FsLab/issues/137, and would prefer not to take a dependency on a pre-release package.

thanks!

**Comment by dsyme** [comment]
super thanks

**Comment by drivehappy** [comment]
We're also waiting on this release, as the 2.4.x version is causing some problems in recent versions of Visual Studio for us.

**Comment by ovatsus** [comment]
Sorry guys, is going to take a little bit longer. But if you really need it you there's no reason you can't use the 3.0 beta version for now

**Comment by gusty** [comment]
Thanks @ovatsus but actually there is a good reason, if we want to release a new stable version of our libraries we can't make them depend on a version of FSharp.Data that is not yet stabilized.

**Comment by ovatsus** [comment]
I've published 3.0 rc. If no major issue is reported I'll republish it as 3.0 in a week's time

**Comment by ovatsus** [comment]
Done
