### ISSUE TITLE
Assembly version issue in 3.0.0-beta4

### ISSUE THREAD

**Issue by danyx23** [fsharp/FSharp.Data#1184]
It seems that the dlls published in the latest nuget prerelease (3.0.0-beta4) have the assembly version set to 1.0.0 and thus lead to problems when you want to start an application linking against FSharp.Data (the runtime expects an assembly with 3.0.0 to be found). This issue does not exist with 3.0.0-beta3.

**Comment by ovatsus** [comment]
Fixed for the beta5 release
