### ISSUE TITLE
Current master doesn't build

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#1195]
My guess the latest VS2017 update broke it, now when I try to do `build All` I get a bunch of errors like this:

`JsonExtensionsTests.cs(46,32): error CS1705: Assembly 'FSharp.Data' with identity 'FSharp.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'FSharp.Core' with identity 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\Git\FSharp.Data\tests\FSharp.Data.Tests.CSharp\FSharp.Data.Tests.CSharp.csproj]`

**Comment by ovatsus** [comment]
It seems FSharp.Data is being compiled against 4.5.0.0, instead of against 4.3.1.0 as it's supposed to, and the version is also being set as 1.0.0.0, instead of 3.0.0.0

@dsyme, @baronfel, help please! :)

**Comment by baronfel** [comment]
I hope to have some time to look at this later this evening. Maybe it's something simple :D

**Comment by ovatsus** [comment]
I can build both solutions in VS2018 and run all the tests in the VS test runner and it all works, it's just the command line builds which are broken

**Comment by baronfel** [comment]
Few notes:

failures are only on the net45 framework, and some go away when I refactor the packagereferences to include a System.Runtime reference for the net45 target:
```
<ItemGroup Condition="'$(TargetFramework)' == 'net45'" >
    <PackageReference Include="FSharp.Core" Version="4.0.0.1" />
    <PackageReference Include="System.Runtime" Version="4.0.*" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'" >
    <PackageReference Include="FSharp.Core" Version="4.3.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.0" PrivateAssets="All" />
    <PackageReference Include="SourceLink.Embed.PaketFiles" Version="2.8.0" PrivateAssets="All" />
    <DotNetCliToolReference Include="dotnet-sourcelink" Version="2.8.0" />
  </ItemGroup>
```

Once this is done I get a _ton_ of errors around cultureinfo not being allowed to be passed in to `DateTime.ToString(string format, IFormatProvider formatProvider)`, which makes me think that in net45 there's not an overload for `DateTime.ToString(string format, CultureInfo culture)`. Also odd is that I can't cast `CultureInfo.InvariantCulture.DateTimeFormat :> IFormatProvider` despite that type implementing `IFormatProvider`:  https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo?view=netframework-4.5

**Comment by ovatsus** [comment]
If I add System.Runtime I start having a bunch of errors like this:

          C:\Git\FSharp.Data\src\CommonRuntime\StructuralInference.fs(49,18): error FS0001: This expression was expected to have type    'System.Type (System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)'    but here has type    'System.Type (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)' [C:\Git\FSharp.Data\src\FSharp.Data.DesignTime\FSharp.Data.DesignTime.fsproj]

**Comment by dsyme** [comment]
I don't know anything about this part of the problem:

> It seems ...the version is also being set as 1.0.0.0, instead of 3.0.0.0

**Comment by baronfel** [comment]
That may be as simple as checking the Package version msbuild property we set in the script. If your other PR fixes the build errors I can check out the version side of things.
