### ISSUE TITLE
Is there a way to configure parser to parse Json strings with missing attributes?

### ISSUE THREAD

**Issue by kbakhit** [fsharp/FSharp.Data#1210]
For example, Json string that has null boolean value and another one that has that boolean value missing

**Comment by smoothdeveloper** [comment]
Hi @kbakhit, could you check under "Inferring record types" & "More complex object type on root level" on http://fsharp.github.io/FSharp.Data/library/JsonProvider.html

The second one has a sample using `SampleIsList` parameter to the `JsonProvider` which maybe what you  are looking for.

Please let us know!

**Comment by kbakhit** [comment]
@smoothdeveloper Thank you for answering. Your suggestion is the answer I was looking for.
Brilliant stuff.
