### ISSUE TITLE
Can't build netstandard2.0 project with .NET Core

### ISSUE THREAD

**Issue by ThibaultLemaire** [fsharp/FSharp.Data#1211]
I've been trying to add FSharp.Data to my .NET Core project, but can't get it to compile.

```
error FS3031 : The type provider '/home/user/.nuget/packages/fsharp.data/2.4.6/lib/net45/FSharp.Data.dll' reported an error : Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/home/user/Projects/GpxAnalyst/GpxAnalyst/GpxAnalyst.fsproj]
```

Steps to reproduce:

``` sh
dotnet new classlib -lang 'F#'
dotnet add package FSharp.Data
dotnet build
```

System info:

- FSharp.Data = 2.4.6
- .NET Core = 2.1.401
- OS = Arch Linux

**Comment by ovatsus** [comment]
.Net Core is only supported on 3.0

**Comment by ThibaultLemaire** [comment]
What do you mean? That you will only support .Net Core with version 3.0 of FSharp.Data, or that you will only support version 3.0 of .Net Core?

**Comment by baronfel** [comment]
Dotnet core is only supported on the 3.0.0 prereleases of FSharp.Data.

**Comment by ThibaultLemaire** [comment]
For the record, if your intent is just to use FSharp.Data on Linux, it works with mono, just don't try to target netstandard (classlib and the other multiplatform projects).
