### ISSUE TITLE
Compiling error with .net core 3.0 preview

### ISSUE THREAD

**Issue by FedericoBinda** [fsharp/FSharp.Data#1234]
Hi
I am trying to compile a .net core app that references FSharp.Data (3.0) with .net core 3.0 preview. However I get the error

`/usr/local/share/dotnet/sdk/3.0.100-preview-009812/FSharp/Microsoft.FSharp.Targets(265,9): error MSB6006: "RunFsc.sh" exited with code 138.`

The error is triggered when I parse a value to an FSharp.Data data provider. For example, a minimal code that fails is:

```
open FSharp.Data

type Simple = JsonProvider<""" { "name":"John", "age":94 } """>
    
[<EntryPoint>]
let main _ =
    let simple = Simple.Parse(""" { "name":"Tomas", "age":4 } """)
    0

```
If I comment the line where I parse a value the error disappears.
Can you please look into the issue?

**Comment by MarneeDear** [comment]
I was able to get version 3.3.3 to compile normally on .net core 3.1

**Comment by FedericoBinda** [comment]
Now it works. Closing the issue. Thanks
