### ISSUE TITLE
Improve Compile Speed?

### ISSUE THREAD

**Issue by benmp** [fsharp/FSharp.Data#1244]
Hello,

I am a beginner here so forgive me if this is naive/wrong.

I created an empty solution and added a Library and a Console Application that references it.

I added FSharp.Data to the package for the Library and declared my type in there.

```
namespace Library
module Say =
    type MyXMLProvider = FSharp.Data.XmlProvider<const(__SOURCE_DIRECTORY__ + "../../data/sample2.xml")>
```

This Library compiles in ~25 seconds.  The XML file in question is 900k lines long, so this seems pretty decent.

The issue I have is the App itself also takes 25 seconds to build on every edit, even just adding a blank line.
```
[<EntryPoint>]
let main argv =
    let myXMLProvider = Library.Say.MyXMLProvider.GetSample
```

Is this expected behavior?  Is there any project/solution setup that I can make to avoid this edit/compile/run ~30s cycle?  The program itself runs in < 1 second, its the compile time that takes forever.

I know that FSI exists, but I am on Mac so I had some trouble using the #r syntax to import FSharp.Data into the Mono FSI window.

Is using a .xsd the answer since my file is so large?

Thanks!

**Comment by realvictorprm** [comment]
I'm not completely sure but to my knowledge at least putting a type from a type provider in a separate file should help with intellisense performance if you edit the other files depending on that type.
