### ISSUE TITLE
Inadequate escaping of query parameters

### ISSUE THREAD

**Issue by graydon** [fsharp/FSharp.Data#1263]
Another request-to-revert: I spent the day tracking down an inadequate level of escaping in query parameters (in my case, `+` characters in query parameters that pass through `EscapeUriString` unescaped, then get un-URL-escaped on the receiving side as spaces) due to https://github.com/fsharp/FSharp.Data/issues/1137. Since `Http.Request` _does_ pass its input through `EscapeUriString`, I can't exactly work around it by escaping myself -- the `%2F` I would substitute itself gets escaped to `%252F`. So I'm actually having to avoid using the whole `Http.Request` subsystem because of this.

`EscapeDataString` may make ugly URLs, but they're at least correctly escaped. Could `Http.Request` be changed back to use it?

**Comment by paulgartner1** [comment]
Please revert this change, I've had to work around this by manually building the URL query string, and avoiding the use of query parameter argument.
Again this seems to be due to #1137 

For example `EscapeDataString` will correctly percent escape characters such as `"+" "&"` where as `EscapeUriString` will not.

**Comment by dsyme** [comment]
@paulgartner1 Could you send a PR to make the revert and we can discuss?  It's going to be tricky to revert if there are chances that people are relying on the new behaviour, but I suspect we should make it "do the right thing" for sure, even if painful

**Comment by RomanStadlhuber** [comment]
Dropping in because I have the same issue. Is there any progress regarding the PR which is still open?
