### ISSUE TITLE
How to parse a list of a JsonProvider type?

### ISSUE THREAD

**Issue by supermihi** [fsharp/FSharp.Data#1285]
In REST APIs you usually have a base (list) resource `/api/entities` which returns a `Entity list`, but also need the underlying (single) type `Entity` for e.g. `POST`s. My approach is to provide the base type:

`type Entity = JsonProvider<"./api-samples/entities.json", SampleIsList=true>`

But then, how do I parse the list when accesssing `/api/entities`? I would need something like `Entity.AsList.Parse('...').`

**Comment by joshuapassos** [comment]
`SampleIsList=true` is to define only one element from list. If you want to use all list use this approach:
```
type Entity = JsonProvider<"./api-samples/entities.json">
let myList = Entity.Parse("...") // json with entity list
```
[Examples](https://fsharp.github.io/FSharp.Data/library/JsonProvider.html)

**Comment by supermihi** [comment]
Thanks for your response. Does that mean, if I have a json file for a single entity only, it is not possible to parse a list of the same type?

**Comment by fpellet** [comment]
@supermihi you can use new feature ParseList (#1272)

**Comment by supermihi** [comment]
Great, thank you!
