### ISSUE TITLE
How to construct absolute URL by combining a “base URL” with relative path

### ISSUE THREAD

**Issue by eduardogoncalves** [fsharp/FSharp.Data#1288]
How can we construct a full (“absolute”) URL by combining a “base URL” (base) with another URL (url). For example, when I scrap a page, some **href** are relative paths, like **'2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html'** or **'/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html'**. How can I get full url from this relative path?

In Python we can use [urljoin](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin):
```python
>>> urljoin("https://www.saibatudomt.com.br/", "2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html")
'https://www.saibatudomt.com.br/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html'

>>> urljoin("https://www.saibatudomt.com.br/", "/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html")
'https://www.saibatudomt.com.br/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html'

>>> urljoin("https://www.saibatudomt.com.br/", "https://www.saibatudomt.com.br/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html")
'https://www.saibatudomt.com.br/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html'
```

**Comment by stuartbright** [comment]
This functionality exists in the `System.Uri` class:
https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-2.2#System_Uri__ctor_System_Uri_System_String_

You can use it to implement your own `urlJoin` function like this:
```
open System

let urlJoin baseUrl (relativeUrl : string) =
    Uri(Uri(baseUrl), relativeUrl).ToString()
```

Example usage:
```
> urlJoin "https://www.saibatudomt.com.br/" "2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html";;
val it : string = "https://www.saibatudomt.com.br/2019/09/cuiaba-bancos-sao-condenados-por-transferir-dinheiro-para-conta-errada.html"
```

**Comment by eduardogoncalves** [comment]
😊 @stuartbright thank you!
