### ISSUE TITLE
Match columns based on name in CSV

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Data#136]
Given a CSV file that looks like this:

```
Date,Open,High,Low,Close,Volume,Adj Close
2012-01-27,29.45,29.53,29.17,29.23,44187700,29.23
2012-01-26,29.61,29.70,29.40,29.50,49102800,29.50
2012-01-25,29.07,29.65,29.07,29.56,59231700,29.56
```

It would be nice if I could specify that I only want to access e.g. `Open` and `Close` columns and I want to expose them as `float`:

```
type Stocks = CsvProvider<"msft.csv", Schema="Open (float), Close (float)">
```

At the moment, the schema specifies "renaming" for the columns rather than "matching". Both options have their uses. The matching is nice because it is a bit more robust - the produced type should be able to handle data files where the columns are re-ordered.

(There is a large number of cases here, so this is tricky....)

PS: This is based on a discussion with a user of the type provider I had recently.

**Comment by NickLydon** [comment]
The CsvProvider doesn't appear to match columns based on name, but rather by order. We have a supplier that occasionally gives us a file with new columns dropped in the middle, which breaks our application. Is there a way to get it to match by name with the schema property?
