### ISSUE TITLE
JsonProvider does not work in FSI past v3.3.3

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FSharp.Data#1361]
Create a .fsx file

```
#r "nuget: FSharp.Data"

open FSharp.Data

type TheJson = 
    JsonProvider<"""{"simple":"simpleValue","value":[{"Id":26,"simple_Number":"35-129-24115-0000"}]}""">
```

`JsonProvider` is not recognized (red squigglies).

Change the reference to `#r "nuget: FSharp.Data, 3.3.3"` and it works.

Explicitly referencing 4.0.0 or 4.0.1 likewise fail.

Environment: Visual Studio 16.9.1
Enable script debugging - true
Enable preview language features - false
Use .NET Core Scripting -true
64-bit F# Interactive - true
F# Interactive options --optimize
Shadow copy assemblies - true

**Comment by nhirschey** [comment]
This appears to be a visual studio bug. @jackfoxy do you want to close this issue and file the bug in the fsharp visual studo repo?

In vs19, the code runs in fsi but I get the same squigglies as you in 16.9 preview 5. However type checking works correctly in ionide:

![image](https://user-images.githubusercontent.com/5226115/111830218-909c9000-88e5-11eb-82c8-54eb4a5e10bd.png)

**Comment by jackfoxy** [comment]
OK, go ahead and close and I will report the bug from VS, Thanks, @nhirschey
