### ISSUE TITLE
Create a code only NuGet package containing ProvidedTypes.fs and .fsi

### ISSUE THREAD

**Issue by mavnn** [fsharp/FSharp.Data#288]
Would this be the right project to do it in? It seems to have the most up to date versions of the files and the ones under most actively maintained.

If people are happy with the idea, I'm more than happy to put together the nuspec required.

@dsyme @ovatsus @tpetricek ?

Via a twitter conversation involving @forki and https://twitter.com/yukitos

**Comment by smoothdeveloper** [comment]
@charlesroddie I think it makes debugging a TP even more of a pain, when you need to see what is occurring in the TP SDK.

**Comment by dsyme** [comment]
There is a nuget available https://www.nuget.org/packages/FSharp.TypeProviders.SDK

However historically we've had trouble with type providers that have significant dependencies, especially when they clash with dependencies in other type providers or in the host tooling.  Part of this came from the way type providers were originally packaged.

These days things are significantly better these days now type providers are all under `typeproviders/...` in the nuget packages, and the build tooling packages their dependencies, but it's still an area where simplifying the dependency chain to include fewer components seems wise.
