### ISSUE TITLE
Yahoo Finance Type Provider

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#39]
I'm not sure if this fits within FSharp.Data or not, but it does seem like a fairly common use case. We already use yahoo data in the CSV samples, but like WorldBank, where we can use the Json TP, having a dedicated TP is much better.

Some links with info on the API:
http://code.google.com/p/yahoo-finance-managed/wiki/CSVAPI
http://developer.yahoo.com/yql/
http://www.jarloo.com/yahoo-stock-symbol-lookup/

**Comment by avjgit** [comment]
Link to mentioned specific YQL item - https://github.com/fsprojects/FSharp.Data.Toolbox/issues/10
