### ISSUE TITLE
Consider adding Parent navigation to HtmlElement

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#533]
This would probably changing this:

```
type HtmlElement =
    | HtmlElement of name:string * attributes:HtmlAttribute list * elements:HtmlElement list
    | HtmlText of string
    | HtmlScript of string
    | HtmlStyle of string
    | HtmlComment of string

type HtmlDocument = 
    | HtmlDocument of docType:string * elements:HtmlElement list
```

To this:

```
type HtmlElement =
    | HtmlElement of name:string * attributes:HtmlAttribute list * elements:HtmlElement list * parent:HtmlElement option
    | HtmlText of string
    | HtmlScript of string
    | HtmlStyle of string
    | HtmlComment of string
```

(note the absence of HtmlDocument)

Also, do we need HtmlScript and HtmlStyle?

**Comment by maestrow** [comment]
Why this issue was closed? As far as I understand currently there is no way to get parent from HtmlNode, isn't it? However this is necessary feature.

**Comment by ErikSchierboom** [comment]
I also stumbled upon this, as was a bit surprised it was not there. Is there any way to get at a node's parent?

**Comment by DroiPlatform** [comment]
`
namespace dowTool
#if INTERACTIVE

#I @"C:\Users\Administrator\.nuget\packages\fsharp.data\3.1.1\lib\net45"
#r @"FSharp.Data.dll"
#endif
open FSharp.Data
open System.IO
open System.Collections.Concurrent

//fsi.AddPrinter(fun (x : HtmlNode) -> null);;

type CD<'Tk, 'Tv> = ConcurrentDictionary<'Tk, 'Tv>
type GL<'T> = System.Collections.Generic.List<'T>

and TNode = {
    value:HElem
    mutable childs:TL
}
    with static member trivial = {value = HNone; childs = null}
and HElem =
    | KeyHNode of KElem
    | HNode of NElem 
    | HLeaf of Leaf
    | HNone
and KElem = {
    mutable id:string
    mutable tag:string
    mutable name:string option
    mutable attr:HA 
    hn:HtmlNode
    parent:TNode ref
}
and NElem = {
    mutable tag:string
    mutable name:string option
    mutable attr:HA 
    hn:HtmlNode
    parent:TNode ref
}
and Leaf = {
    hn:HtmlNode
    mutable value:string
    parent:TNode ref
    mutable ltyp:int
}
//and HL = GL<HElem>
and TL = GL<TNode>
and HA = GL<HtmlAttribute>

module htmlHelper = 
    let hnCD = CD<string, HtmlNode>()
    let keCD = CD<string, KElem>()
    let ktnCD = CD<string, TNode>()
    let hn2HElem (hn:HtmlNode) (parent:TNode ref) =
        match hn with
        | HtmlElement (name:string, attributes:HtmlAttribute list, elements:HtmlNode list) ->
            //let (HtmlElement (name:string, attributes:HtmlAttribute list, elements:HtmlNode list)) = dElems.[1]
            let keyMetadata = 
                attributes 
                |> List.choose (fun (HtmlAttribute (nm, v)) -> 
                    let nml = nm.ToLower() 
                    match nml = "id" || nml = "name" with
                    | true -> Some (nm, v)
                    | false -> None
                    )
                |> Dict.ofList
            match keyMetadata.ContainsKey "id" with
            | false ->
                let he = {
                    tag = name
                    name = keyMetadata |> Dict.existSomeOrNone "name"
                    attr = attributes |> List.toGenList<HtmlAttribute>
                    hn = hn
                    parent = parent
                }
                (HNode he), elements
            | true ->
                //let hn = dElems.[1]
                //let parent = TNode.trivial
                let id = keyMetadata.["id"]
                let he = {
                    id = id
                    tag = name
                    name = keyMetadata |> Dict.existSomeOrNone "name"
                    attr = attributes |> List.toGenList<HtmlAttribute>
                    hn = hn
                    parent = parent 
                }
                hnCD.TryAdd(id, hn) |> ignore
                keCD.TryAdd(id, he) |> ignore
                (KeyHNode he), elements
        | HtmlText (content:string) ->
            HLeaf {
                hn = hn
                value = content
                parent = parent
                ltyp = 0
            }, []
        | HtmlComment (content:string) ->
            HLeaf {
                hn = hn
                value = content
                parent = parent
                ltyp = 1
            }, []
        | HtmlCData (content:string) ->
            HLeaf {
                hn = hn
                value = content
                parent = parent
                ltyp = 2
            }, []
    let helem00, hnls00 = hn2HElem dElems.[0] (ref TNode.trivial)
    let helem01, hnls01 = hn2HElem dElems.[1] (ref TNode.trivial)
    let treeTransformation (hnl:HtmlNode list) =
        //let tnref = ref (Unchecked.defaultof<TNode>)
        let rec treeTransformWrapper (hnl:HtmlNode list) (parentNodeRef:TNode ref) =
            let rec treeTransform (hn:HtmlNode) (parentNodeRefI:TNode ref) (curNodeRef:TNode ref) =
                let nodeValue, elems = hn2HElem hn parentNodeRefI
                let tn =
                    match elems.Length with
                    | 0 ->
                        {//HTNode {
                            value = nodeValue
                            childs = null
                        }  
                    | _ ->
                        {//HTNode {
                            value = nodeValue
                            childs = treeTransformWrapper elems curNodeRef
                        }
                match nodeValue with
                | KeyHNode kn ->
                    let id = kn.id
                    ktnCD.TryAdd(id, tn) |> ignore
                | _ -> ()
                tn         
            hnl
            |> List.map (fun hn ->
                let curNodeRef = ref (Unchecked.defaultof<TNode>)
                curNodeRef.Value <- treeTransform hn parentNodeRef curNodeRef
                curNodeRef.Value
                )
            |> List.toGenList<TNode>
        let tree = treeTransformWrapper hnl (ref TNode.trivial)
        tree
    //printfn "====================getTree===================="
    //let tree = treeTransformation dElems
    //printfn "====================getTree done==============="
    // tree.Count
    // tree.[0]
    //let (HTNode htn) = tree.[1]
    let htn = tree.[1]
    // htn.childs.Count
    // htn.childs.[0]
    // htn.childs.[1].childs.Count
    // htn.childs.[1].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.[6]
    // htn.childs.[1].childs.[0].childs.[0].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.[0].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.Count
    // htn.childs.[1].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.[0].childs.Count
    let drawTagTree (tn:TNode) =
        let rec drawTagTreeBase (tn:TNode) (lv:int) =
            match tn.value with
            | KeyHNode kn ->
                printfn "[%s] <%s> id:%s" (lv.ToString().PadLeft(5, '.')) kn.tag kn.id
            | HNode nn -> 
                printfn "[%s] <%s>" (lv.ToString().PadLeft(5, '.')) nn.tag
            | HLeaf lf ->
                printfn "[%s] {%d}" (lv.ToString().PadLeft(5, '.')) lf.ltyp
            | HNone ->
                printfn "orz"
            let lvnxt = lv + 1
            match tn.childs with
            | null -> ()
            | _ ->
                tn.childs
                |> Seq.iter (fun chtn ->
                    drawTagTreeBase chtn lvnxt
                    )
         
        drawTagTreeBase tn 0
    // drawTagTree htn
    // drawTagTree ktnCD.[""]
    let (KeyHNode canvaskhn) = ktnCD.[""].value
    // canvaskhn.parent.Value.childs
    // canvaskhn.parent.Value.GetType().Name
    // canvaskhn.parent.Value.value.GetType().Name
    // canvaskhn.parent.Value.childs |> Seq.map (fun x -> x.GetType().Name)
    // canvaskhn.parent.Value.childs 
    // |> Seq.mapi (fun i x -> 
    //     match x.value with
    //     | KeyHNode ke -> i, ke.id
    //     | _ -> i, null
    //     )
    let traverseTree (tn:TNode) (op:TNode->int->unit) =
        let rec traverseTreeBase (tn:TNode) (lv:int) =
            op tn lv
            let lvnxt = lv + 1
            match tn.childs with
            | null -> ()
            | _ ->
                tn.childs
                |> Seq.iter (fun chtn ->
                    traverseTreeBase chtn lvnxt
                    )
         
        traverseTreeBase tn 0
    //traverseTree ktnCD.[""] (fun tn lv -> printfn "%A" tn)
    let traverseTreeList (tnl:TL) op =
        seq[0..(tnl.Count - 1)]
        |> Seq.iter (fun idx ->
            traverseTree tnl.[idx] op
        ) 
    printfn "====================清空body===================="
    traverseTreeList tree (fun tn lv -> 
        match tn.value with
        | KeyHNode ke ->
            match ke.id with
            | ""
            | "" ->
                tn.childs <- null
            | _ -> ()
        // | HNode ne -> 
        //     match ne.tag with
        //     | "body" ->
        //         printfn "123"
        //         tn.childs <- [ktnCD.[""]] |> List.toGenList<TNode>
            | _ -> ()
        | HNode ne -> 
            match ne.attr |> Seq.exists (fun (HtmlAttribute (k, v)) -> k = "class" && v = "uxb-toolBarWrap") with
            | false -> ()
            | true ->
                ne.parent.Value.childs <- null

        | _ -> ()
        )
    let tree2Dom (tn:TNode) =
        let rec toDom:TNode->int->HtmlNode option =
            fun tn lv ->
                //let tn = htn.childs.[1]
                let helem = tn.value
                //let (HNode ke) = helem
                match helem with
                | HNone -> None
                | _ ->
                    let lvnxt = lv + 1
                    match helem with
                    | KeyHNode ke ->
                        let attrs = 
                            ke.attr
                            |> Seq.map (fun (HtmlAttribute (k, v)) ->
                                k, v)
                            |> Seq.append (
                                match ke.name with
                                | Some nm ->
                                    seq["name", nm]
                                | None -> seq[]
                                |> Seq.append
                                    (seq["id", ke.id]))
                        
                        let innerHN = 
                            match tn.childs with
                            | null when ke.tag <> "input" && ke.tag <> "img" ->
                                    seq[HtmlNode.NewText("")]
                                | null -> Seq.empty
                            | _ ->
                                tn.childs
                                |> Seq.choose (fun tni ->
                                    toDom tni lvnxt
                            ) 
                        HtmlNode.NewElement(ke.tag, attrs, innerHN) |> Some
                    | HNode ne ->
                        let attrs = 
                            ne.attr
                            |> Seq.map (fun (HtmlAttribute (k, v)) ->
                                k, v)
                            |> Seq.append (
                                match ne.name with
                                | Some nm ->
                                    seq["name", nm]
                                | None -> seq[]
                                )
                        let innerHN = 
                            match tn.childs with
                            | null when ne.tag <> "input" && ne.tag <> "img" ->
                                    seq[HtmlNode.NewText("")]
                            | null -> Seq.empty
                            | _ ->
                                tn.childs
                                |> Seq.choose (fun tni ->
                                    toDom tni lvnxt
                            ) 
                        HtmlNode.NewElement(ne.tag, attrs, innerHN) |> Some
                    | HLeaf lf ->
                        match lf.ltyp with
                        | 0 ->
                            HtmlNode.NewText lf.value |> Some
                        | _ ->
                            None
                    | HNone -> None
        toDom tn 0
    let (Some dom) = tree2Dom tree.[1]

    //System.IO.File.WriteAllText(@"", ("<!DOCTYPE HTML>\r\n" + dom.ToString())) |> ignore
    // dElems.[0].Name()
    // let head = HtmlNode.descendants false (fun _ -> true) dElems.[0] |> Seq.item 0
    // head.Name()
    // HtmlNode.descendants false (fun _ -> true) head
    // (dElems.[0].Descendants() |> Seq.item 1).Name()
    // (dElems.[0].Descendants() |> Seq.item 12).Name()
    // let hn = HtmlDocumentExtensions.Body ss
    // let tbl00 = HtmlDocumentExtensions.Descendants(ss, "table", false) |> Seq.item 0
    // let tbl01 = HtmlDocumentExtensions.Descendants(ss, "table", false) |> Seq.item 1
    // let tbl02 = HtmlDocumentExtensions.Descendants(ss, "table", false) |> Seq.item 2
    // File.WriteAllText(@"c:\taifex\001.html", tbl01.ToString())
    // File.WriteAllText(@"c:\taifex\ss.html", ss.ToString())
    // let alltr = tbl01.Descendants() |> Seq.filter (fun hn -> (HtmlNode.name hn) = "tr")

    // alltr |> Seq.item 2
    // let header02 = alltr |> Seq.item 4
    // let dataRow01 = alltr |> Seq.item 5
    // let dataValue01 = 
    //     (alltr |> Seq.item 5).Descendants() 
    //     |> Seq.map (fun hn -> 
    //         printfn "%A" <| HtmlNode.attributeValue "rowspan" hn
    //         HtmlNode.innerText hn
    //         ) 
    //     |> Seq.toArray
    // let dataValue02 = (alltr |> Seq.item 6).Descendants() |> Seq.map (fun hn -> HtmlNode.innerText hn) |> Seq.toArray
    // (alltr |> Seq.item 5).Elements()
    // tbl01.GetType().Name
    // (tbl01.Descendants() |> Seq.item  0).GetType().Name
    // tbl01.Descendants() |> Seq.length   
  
    // let tblElems = tbl01.Descendants(fun x -> x.Name() = "tr") |> Seq.length
    // let trs = HtmlNode.descendants true (fun n -> n.Name() = "tr") tbl01
    // trs |> Seq.item 0 
    // // taifex3_7_12_5().Tables |> Seq.length
    // // let rawStats = taifex3_7_12_5().Tables.``Version History``
    // // printfn "%A" (rawStats.Rows)
    // let a = hn.Elements()
    // a.Length

    // let t00_01 : HtmlNode = HtmlNode.descendants false (fun _ -> true) tbl00 |> Seq.item 0 
    // HtmlNode.NewElement("tr")
    // HtmlNode.NewElement("tr", seq["class", "orz"; "class", "orz"])
    // HtmlNode.NewText("orz")
    // HtmlNode.NewText("orz").GetType().Name
    // HtmlNode.NewElement("tr", seq["class", "orz"; "class", "orz"], seq[HtmlNode.NewText("orz")])
    // Say.hello "orz"
    // //System.Console.ReadKey() |> ignore
    // 0
`
