### ISSUE TITLE
Json parser issues

### ISSUE THREAD

**Issue by mrange** [fsharp/FSharp.Data#563]
Hi.

As a weekend project I thought I replace the JSON parser in FSharp.Data for fun. 

While comparing the existing JSON parser with my weekend project I found some potential issues in the existing JSON parser:
1. {"\"":null} fails to parse correct: It's parsed as {"":null}
2. 0 parses successfully but shouldn't, jsonlint and the spec agrees that only arrays and objects are allowed at root level
3. [0123] parses successfully but shouldn't, jsonlint and the spec agrees that no digits may follow a leading zero

IMHO a parser must be strict as developers tend to trust the implementation. If the implementation isn't strict developers will generate JSON that aren't standard compliant thus undermining the purpose of having a standard to begin with.

Also, personally I think it's problably contra-productive to parse numbers as decimals (and sometimes floats). The reason being that JSON is coming from the JavaScript world. JavaScript represents numbers as  64bit binary floating point values ie double. .NET has much more capable numerics and implementations might therefore chose to support decimals and int64s. However, when sending this info to the JavaScript world if you have big 64 bit numbers they won't fit into a double. Devs will then unknowingly create JSON documents that can't be successfully consumed by JavaScript.

For example: the TwitterStream.json sample data has "id" members as well as "id_str" members probably because "id":263290764698718209 can't be exactly represented as a double.

Thanks for a great library

**Comment by duncanmak** [comment]
Is there a reason why `parseRootValue` in `JsonValue.fs` doesn't support parsing simple numbers and other non "collection" literals?

```
> JsonValue.Parse("1");;    
System.Exception: Invalid JSON starting at character 0, snippet = 
----
1
-----
json = 
------
1
-------
```

It seems like a handy behavior to allow other literals at the root level.
