### ISSUE TITLE
MissingMethodException when using FSharp.Data in a PCL

### ISSUE THREAD

**Issue by tgnm** [fsharp/FSharp.Data#605]
Not sure why I keep getting this exception:

```
Result Message: System.MissingMethodException : Method not found:
 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String)'.
```

 I have tried different FSharp.Core binding redirects and I still have issues.

The PCL profile I am using is 47 (new Portable library in VS 2013).

I am not entirely sure but it seems to be related to this issue: https://github.com/fsharp/FSharp.Data/issues/398

I have also posted a question on SO: http://stackoverflow.com/questions/23389752/missingmethodexception-when-running-a-unit-test-that-uses-fsharp-data

**Comment by kerams** [comment]
I'm seeing the exact same thing on netcoreapp5.0. I assume it's a problem with the .NET 5 SDK preview?

**Comment by xperiandri** [comment]
No, Core 3.1 + F# 4.7.1 gives the same result

**Comment by OlegZee** [comment]
I noticed the same in FAKE build script referencing FSharp.Data. I have no .NET 5 preview installed.

>".fake/fake.exe" --version
FAKE 5 - F# Make (5.20.0)
FakePath: ......\.fake\.store\fake-cli\5.20.0\fake-cli\5.20.0\tools\netcoreapp2.1\any\Fake.Runtime.dll
Paket.Core: 5.245.1

>dotnet --version
3.1.201

**Comment by serjebulavsky** [comment]
@OlegZee Same, don't have .NET 5 and still get this error.
