### ISSUE TITLE
Some tests fail only when the OS's time zone is non-UTC

### ISSUE THREAD

**Issue by lilred** [fsharp/FSharp.Data#607]
As I am in Montreal, my OS's time zone is UTC-5. This causes this test to fail.

https://github.com/fsharp/FSharp.Data/blob/master/tests/FSharp.Data.Tests/HttpIntegrationTests.fs#L181

**Comment by phongphan** [comment]
The `DateTimeKind.Unspecified` is treated as `Local` when convert to UTC. `HttpWebRequest.Date` and `HttpWebRequest.IfModifiedSince` setter doing this internally.

The `GMT` doesn't seem to recognized by the DateTime parser.
```
> DateTime(1999, 12, 31, 11, 59, 59).ToUniversalTime() = DateTime.ParseExact("Fri, 31 Dec 1999 11:59:59 GMT", "R", CultureInfo.InvariantCulture);;
val it : bool = false
```

**Comment by ovatsus** [comment]
I believe this has been fixed already
