### ISSUE TITLE
Json Type Provider does not expose full graph in some instances

### ISSUE THREAD

**Issue by jamessdixon** [fsharp/FSharp.Data#643]
I am using SkyBiometry's API and I have this LOC:

type skybiometryFaceRecognition = JsonProvider<"http://api.skybiometry.com/fc/faces/recognize.json?uids=sarahConnor@ChickenFace&urls=https://lg2014dev.blob.core.windows.net/d69bdda9-d934-448c-acae-99019f3a564f/01ee184f-ff0b-426f-872a-cbc81ef58d90.jpg&api_key=XXXXX&api_secret=YYYY">

When I run it in the REPL, everything comes in.  Here it is in part:
      "tags": [
        {
          "uids": [],
          "label": null,
          "confirmed": true,
          "manual": false,
          "width": 20.0,
          "height": 26.67,
          "yaw": 0,
          "roll": -2,
          "pitch": 0,
          "attributes": {
            "face": {
              "value": "true",
              "confidence": 47
            }

When I try and use it via intellisense, I get only:
            recognition.Photos.[0].Tags.[0].Attributes

The face+ graph is missing

**Comment by ovatsus** [comment]
Closing as there's no repro
