### ISSUE TITLE
Xml type encoding

### ISSUE THREAD

**Issue by thinkbeforecoding** [fsharp/FSharp.Data#651]
The XmlProvider has a Culture parameter to specify the culture used to create Xml documents.

By default it uses invariant culture and converts all values to string.

But there are a bunch of quite standard format (the one used in XmlConvert) that are directly handled by XElement when values are passed as boxed objects.
The main problem here is with DateTime. The de facto standard for Xml dates is `yyyy-MM-ddTHH:mm:ss` but current implementation will default to `dd/MM/yyyy HH:mm:ss`

If it's difficult to set it as new default, maybe it could be interesting to add a xml formatting parameter for this ?

**Comment by ovatsus** [comment]
This is now fixed
