### ISSUE TITLE
Http - use HttpUtility.UrlEncode instead of Uri.EscapeDataString for FormValues

### ISSUE THREAD

**Issue by theimowski** [fsharp/FSharp.Data#675]
I use api that accepts large input as form-value in body of http post. `Uri.EscapeDataString` has a length limit of 65520, and throws 
_System.UriFormatException: Invalid URI: The Uri string is too long._
Uri.EscapeDataString doesn't have this restriction. Further reading: http://blog.nerdbank.net/2009/05/uriescapedatapath-and.html

edit: unfortunately HttpUtility.UrlEncode is in System.Web assembly, would have to add it to references

**Comment by haf** [comment]
HttpUtility has bugs that doesn't make it suitable for uri encoding strings, so I would advice against it.

**Comment by jkodroff** [comment]
I think RestSharp [had the same issue](https://github.com/restsharp/RestSharp/pull/247) and resolved it by chunking the string.

**Comment by prosconi** [comment]
+1 Just ran into this, annoying.

**Comment by Gastove** [comment]
Any chance anyone's found a work-around for this?

**Comment by ovatsus** [comment]
Fixed by #1104
