### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by fsgit** [fsharp/FSharp.Data#678]
The Travis build on OSX is failing recently (it may be a timeout)

https://travis-ci.org/fsharp/FSharp.Data/builds

**Comment by ovatsus** [comment]
I removed the GetCustomAttributes from the tests, it's not worth the trouble of having tests failing all the time in Mono

**Comment by ovatsus** [comment]
https://github.com/fsharp/FSharp.Data/commit/2150251c03d7d03ff5c4eb92b0330b001ff85c68

**Comment by ovatsus** [comment]
In any case, @rneatherway, did you get to create a Mono bug for this?

**Comment by rneatherway** [comment]
No I never got around to it. I would prefer to give a simple reproduction, but I didn't have time to create one.
