### ISSUE TITLE
JsonProvider should serialize DateTime as ISO 8601

### ISSUE THREAD

**Issue by danielrbradley** [fsharp/FSharp.Data#689]
When using the JsonProvider with DateTime parameters, it currently serializes the DateTime using the local environment settings. 

In my opinion, it would be preferable to always format dates in JSON using [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601).

    #r "../packages/FSharp.Data.2.0.15/lib/net40/FSharp.Data.dll"
    open FSharp.Data
    open System

    type JsonType = JsonProvider< """{"date":"2000-01-01T20:50:54Z"}""" >

    let now = DateTime.UtcNow
    let expected = sprintf """{"date":"%sZ"}""" (now.ToString("s"))
    let actual = JsonType.Root(now).JsonValue.ToString(JsonSaveOptions.DisableFormatting)

    (* Prints something like:
        expected: {"date":"2014-09-25T10:05:10Z"}
        actual:   {"date":"09/25/2014 10:05:10"} *)
    printfn "expected: %s" expected
    printfn "actual:   %s" actual

**Comment by ovatsus** [comment]
Any progress on this?
