### ISSUE TITLE
HTTP Custom headers [Cookies]

### ISSUE THREAD

**Issue by xenocons** [fsharp/FSharp.Data#695]
Http module is seemingly stripping headers from request if name is Cookie, I would expect the behaviour to throw an exception if cookies being disallowed manually is desired behaviour, silently stripping the header is not preferable.

let req = Http.Request("http://www.google.com", headers = ["a","test"] )

Generates:
```
GET http://www.google.com/ HTTP/1.1
a: test
Host: www.google.com
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
```

let req = Http.Request("http://www.google.com", headers = ["Cookie","b"] )

Generates:
```
GET http://www.google.com/ HTTP/1.1
Host: www.google.com
Accept-Encoding: gzip, deflate
```

I am confused why this happens, after looking at the source, I thought it must be a .NET issue, however the following behaviour was exhibited by .NET

```
let x = WebRequest.Create("http://www.google.com") :?> HttpWebRequest
x.Headers.Add("Cookie","a")
x.GetResponse()
```
Generates:
```
GET http://www.google.com/ HTTP/1.1
Cookie: a
Host: www.google.com
```
Edit: Fixed up first example response.

**Comment by ovatsus** [comment]
Any progress on this?

**Comment by xenocons** [comment]
Sorry for the late reply, I have given up on this for the time being, it is too complicated and also security sensitive, I am worried I will only make it worse in my attempts.
