### ISSUE TITLE
HtmlProvider error: Index was outside the bounds of an array

### ISSUE THREAD

**Issue by weismat** [fsharp/FSharp.Data#746]
I am trying to use the HTML provider on some internal data which works fine on a browser.
When trying to use it via 
<code>
type XxxType=HtmlProvider<...>
</code>
I get the error message "The type provider 'ProviderImplementation.HtmlProvider' reported an error: Index was outside the bounds of an array. Unfortunately I can not add the html here. 
Could you point me to a got way to debug this problem, so that I can provide a fix.

**Comment by ovatsus** [comment]
This fix was already merged
