### ISSUE TITLE
[CSV] Allow parsing of single rows

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FSharp.Data#752]
Once you've generated a typed CsvProvider, sometimes it is handy to be able to chuck single (or multiple) rows of data at the provider to parse and process. Currently you have to also provide the header row in the string that is passed to the Parse method as well. It would be useful to simply be able to call the Parse method with just the row data without having to provide the headers again e.g.

    type MyDataset = CsvProvider< @"Dataset.csv">
    let row = MyDataset.Parse "Isaac,Abraham,34"

rather than

    let row = MyDataset.Parse "Forename,Surname,Age\r\nIsaac,Abraham,34"

**Comment by ovatsus** [comment]
This should be easy to do, we already have a CsvRow constructor, we can add a CsvRow.Parse method as well.

@nwolverson, do you want to take it?

**Comment by nwolverson** [comment]
Should be able to take a look this week.
