### ISSUE TITLE
Out of memory exception using csv provider on large file

### ISSUE THREAD

**Issue by mofus** [fsharp/FSharp.Data#753]
I am trying to use the csv type provider to load a large csv file.
The file is around 3GB. When I load it, I get an out of memory exception.
I have tried the tip on handling big datasets from [this page](http://fsharp.github.io/FSharp.Data/library/CsvProvider.html).

However, the `CacheRows` option does not change the behavior.
I am unsure if the csv provider is supposed to work on files this big.
I’ve had the same problem with the xml provider [before]( http://stackoverflow.com/questions/26404394/outofmemoryexception-loading-a-large-xml-file-with-f-typeprovider).

I have uploaded my [test project](http://d.pr/f/141xP) for Visual Studio.
Included is both a script and a program that will trigger this error.

I have tried 32- and 64bit, F# 3.1 and 4.0, Visual Studio 2013 update 4 and 2015.
I can get all the data loaded if I split the file into smaller pieces and load them one by one.

Does anyone know if it is possible to load a multi GB file without splitting it?

**Comment by ovatsus** [comment]
I fixed this by only loading the full file for web requests, and not for files: #784
