### ISSUE TITLE
HasHeaders option after creating CsvProvider

### ISSUE THREAD

**Issue by mofus** [fsharp/FSharp.Data#754]
I am using the Csv Provider to parse several large csv files of the same format.

I use a sample file containing the correct headers to create my type provider like so:
`type Measurement = CsvProvider<"sorted100M_sample.csv",CacheRows=false>`

Then I use `Measurement` to load files:
`Measurement.Load("measurements/sorted100MSplit_1")`
These files do not contain headers.

My "problem" is that the first line is skipped on all the subsequent loads.
It would be nice to load with an option to say that the file has no headers.
It is possible when creating the type, but not when loading afterwards.

**Comment by ovatsus** [comment]
@weismat, it should work, please check again in latest master, as I have merged the latest ProvidedTypes.fs

**Comment by weismat** [comment]
I tried to test it using MASTER - received error 
>The type provider constructor has thrown an exception: Type 'FSharp.Data.Runtime.Freebase.FreebaseDataContext' not found"</quote>

**Comment by ovatsus** [comment]
We removed freebase, so that error is weird, I'll double check to see if there's any left overs
In any case if you push your code to your repro, I can have a look

**Comment by weismat** [comment]
I rebuild and the error is gone. But the result is different than I expected.
```
open FSharp.Data
type Test = CsvProvider<"sampleHeaders.csv",CacheRows=false>
[<EntryPoint>]
let main argv = 
    let test = Test.Load("sampleNoHeaders.csv");
    test.Rows |> Seq.iter (fun row -> printf "row:%A" row)
    printfn "%A" argv
```
sampleNoHeaders,csv
1,2
sampleHeaders.csv
Col1,Col2
1,2
