### ISSUE TITLE
CsvProvider: AssumeMissingValues + PreferOptionals not working as expected

### ISSUE THREAD

**Issue by fenchurch1** [fsharp/FSharp.Data#763]
Used the following params:
Sample=fp, AssumeMissingValues=true, PreferOptionals=true

Was expecting all the columns to be of type 'T Option.  However, only those columns with missing values in sample data had the 'T Option data type.  Others came through with the primitive data types (double, int etc)

Works if I manually override with Schema parameter and make all columns 'T Option at compile time. However, I cannot use the schema string dynamically since it needs to be a Literal attribute.

**Comment by ovatsus** [comment]
It seems to work fine for me:

![image](https://cloud.githubusercontent.com/assets/738761/6203615/e680f2b6-b521-11e4-8fea-9038c67a6f7f.png)

If you have a concrete example that doesn't work please reopen
