### ISSUE TITLE
Date fails to be recognized in Windows 10

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#767]

**Comment by ovatsus** [comment]
The problem here is Windows has changed the default time format for nb-NO in Windows 10. In previous Windows releases, the default time format was "HH:mm" but this has changed to "HH.mm". And .NET DateTime.Parse gets confused when both the date and time separators are the same.

So I guess we need to change the unit tests to use another culture, or when date parsing fail, try to find a way to try again forcing it to interpret it as a date only without time component

**Comment by ovatsus** [comment]
Seriously, even this breaks:

        let culture = CultureInfo.GetCultureInfo("nb-NO")
        DateTime.Parse(DateTime.Now.ToString(culture), culture)

Argh!!!

**Comment by colinbull** [comment]
@ovatsus This breaks the tests on both my windows 7 and windows 8 machines now. Reverting back to nb-NO fixes things. I'll keep it as pt-PT for the minute, and just use nb-NO so I can get things compiling, and tests running. Going forward though isn't this going to cause problems?

**Comment by ovatsus** [comment]
Weird, it's passing on CI. Try with es, fr, or it, I think they also have the same formatting

**Comment by colinbull** [comment]
I'm not ruling out the domain settings here messing about with the culture settings on my work machine. Yep fr-FR seems to work, so I'll push this and keep an eye on the build.
