### ISSUE TITLE
FSharp.Data does not play so well with FunScript, createRecord

### ISSUE THREAD

**Issue by jruizaranguren** [fsharp/FSharp.Data#770]
According to [FSharp.Data home page] (https://github.com/ZachBray/FunScript/issues/152), it plays well with FunScript. I have been doing some tests and have found some problems with CreateRecord.

I have reviewed [FunScript.Data] (https://github.com/ZachBray/FunScript/blob/master/src/data/FunScript.Data/JsonProvider.fs) where mappings to JsonProvider are defined, but I don't know how could I fix it. 

I have found problems with CreateRecord and asyncReadTextAtRuntimeWithDesignTimeRules static functions so far.

Could you show me how to modify FunScript.Data in order to fix this?

**Comment by ovatsus** [comment]
https://github.com/ZachBray/FunScript/issues/152
https://github.com/ZachBray/FunScript/issues/154

**Comment by ovatsus** [comment]
You need to create mappings for CreateValue, CreateRecord and CreateArray (https://github.com/fsharp/FSharp.Data/blob/master/src/Json/JsonRuntime.fs) in Funscript here: https://github.com/ZachBray/FunScript/blob/master/src/data/FunScript.Data/JsonProvider.fs#L125

**Comment by ovatsus** [comment]
This is being fixed over a FunScript, so closing
