### ISSUE TITLE
XsdProvider fails on Mac

### ISSUE THREAD

**Issue by object** [fsharp/FSharp.Data#776]
I can successfully build XsdProviders branch, but if I try create a provider for a test schema in Xamarin Studio F# Interactive, I get the following error:

/Users/vagif/Documents/Projects/ThirdParties/FSharp.Data/tests/FSharp.Data.Tests/XsdProvider.fs(15,15): error FS3033: The type provider 'ProviderImplementation.XsdProvider' reported an error: System.Exception: Couldn't find a parent for System.Xml.Schema.XmlSchemaSimpleType
  at Microsoft.FSharp.Core.ExtraTopLevelOperators+PrintFormatToStringThenFail@128-1[System.Xml.Schema.XmlSchemaAnnotated].Invoke (System.String message) [0x00000] in <filename unknown>:0 
[...]

It works fine if I run it on Windows.

**Comment by ovatsus** [comment]
XsdProvider is still WIP. Any help would be appreciated
