### ISSUE TITLE
Csv type provider fails with OutOfMemory with large sample file

### ISSUE THREAD

**Issue by evelinag** [fsharp/FSharp.Data#779]
I tried to pass a large sample file into csv type provider:
```
type BigData = CsvProvider<"MyLargeFile.csv",CacheRows=false,InferRows=10>
```
and it fails with OutOfMemoryException. Even thou it shouldn't cache all the rows, it tries to read the entire file.

**Comment by SeanU** [comment]
Coincidentally, I just came to report the same issue.  It also seems to be bringing Visual Studio down in the process.  This is with a 10GB file containing approx. 17.5 million lines .

If I extract out a 10-row sample I can use it to create the type, but trying to work with the file still fails:

```
type BigData = CsvProvider<"MyLargeFile-sample.csv", CacheRows=false>
let csvData = BigData.Load("MyLargeFile.csv")

let ids = 
    csvData.Take(100).Rows 
    |> Seq.map (fun x -> x.Id)

// Fails with OutOfMemoryException here
Seq.length ids
```

**Comment by tpetricek** [comment]
I had a quick look into this and it seems that we are calling `ReadToEnd` on a stream here:

 * https://github.com/fsharp/FSharp.Data/blob/363cca3eeb291931294efe3ec2c30680a10f16bf/src/CommonRuntime/IO.fs#L226

I guess this file is shared with XML and JSON, where we need to read the whole thing into memory anyway, but for CSV files, we should be able to just read first X lines...

**Comment by ovatsus** [comment]
We would need something like AsyncSeq to make this work, this has been discussed before but never implemented: https://github.com/fsharp/FSharp.Data/issues/18

**Comment by tpetricek** [comment]
I don't think we would need full async loading for this - just an option to read only the specified number of lines rather than the entire sample file...

**Comment by ovatsus** [comment]
Yes, your right, if InferRows is specified we could do several ReadLine's instead of the ReadToEnd. Marking as up-for-grabs

**Comment by ovatsus** [comment]
Can anyone provide me a csv file that repros this?

**Comment by ovatsus** [comment]
Found a 8GB one, should repro the problem: http://storage.googleapis.com/freebase-public/deleted_freebase.tar.gz?

**Comment by ovatsus** [comment]
Send PR, second pair of eyes appreciated
