### ISSUE TITLE
Added the ability to add form variables to the Html Type Provider

### ISSUE THREAD

**Issue by jamessdixon** [fsharp/FSharp.Data#780]
Currently, the Html Type Provider's .Load() function does not support adding in form data.  It would be great to have that ability.  Currently, I am using the WebClient.UploadString() method and then the Type Provider's .Parse() function.

**Comment by tpetricek** [comment]
I think the idea is to keep the `Load` methods relatively simple.

That said, you should be able to use `Http.Request` (also [from F# Data](http://fsharp.github.io/FSharp.Data/library/Http.html)) to send the request with form data, which should be simpler than using `WebClient`. I'm not sure if this lets you specify form data - but I think it should! (If not, we can certainly add that...)

So, I think the preferred method would be to use `Http.Request` and `Parse(...)`.

**Comment by tpetricek** [comment]
If more people think we should do this, then we can reconsider this - but for now, I'm closing this issue. Thanks for the suggestion anyway!
