### ISSUE TITLE
Test don't run from command line when .Net 3.5 is not installed

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#782]
Even though we specify 4.0:

        |> NUnit (fun p ->
            { p with
                DisableShadowCopy = true
                TimeOut = TimeSpan.FromMinutes 20.
                Framework = "4.0"
                Domain = MultipleDomainModel
                OutputFile = "TestResults.xml" })

**Comment by ovatsus** [comment]
@forki any idea?

    Starting Target: RunTest_FSharp.Data.Tests
    C:\Git\FSharp.Data\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\Git\FSharp.Data\tests\FSharp.Data.Tests\bin\Release\FSharp.Data.Tests.dll" "-xml:TestResults.xml" "-framework:4.0" "-domain:Multiple"
    C:\Git\FSharp.Data\packages\NUnit.Runners\tools\nunit-console.exe "-nologo" "-noshadow" "-labels" "C:\Git\FSharp.Data\tests\FSharp.Data.Tests\bin\Release\FSharp.Data.Tests.dll" "-xml:TestResults.xml" "-framework:4.0" "-domain:Multiple"
    Running build failed.
    Error:
    System.Exception: NUnit test failed. Process finished with exit code FatalError (-2146232576).
       at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
       at FSI_0001.Build.runTestTask@127.Invoke(Unit unitVar0) in C:\Git\FSharp.Data\build.fsx:line 128
       at Fake.TargetHelper.runTarget@326(String targetName) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 340

**Comment by weismat** [comment]
Do you have any specifig configuration settings? You may test the settings mentioned in this [MSDN](https://msdn.microsoft.com/en-us/library/ee518876%28v=vs.110%29.aspx) entry.

**Comment by DamianReeves** [comment]
Why was this closed? I'm experiencing the same issue on my build server.

**Comment by ovatsus** [comment]
If you find a way to fix it, feel free to send a pull request

**Comment by ngm** [comment]
`nunit-console.exe` doesn't seem to honour the `/framework` setting (or it's for a different purpose).

Including the following in `nunit-console.exe.config` will enable it to run on a machine without .NET 3.5.  

```
<startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0.30319" />
</startup>
```

Presently I just have a template `nunit-console.exe.config` that I copy over the one included in the package, prior to running the tests.
