### ISSUE TITLE
HtmlParser.fs, stackoverflow in 'parser'

### ISSUE THREAD

**Issue by xenocons** [fsharp/FSharp.Data#791]
Hello,

Could someone please confirm the following test case, I have reduced the crash, however, I have noticed this 'in the wild' against a legitimate HTML page (as an aside HtmlParser tries to parse html content that is inside a JSON string and is escaped, is this intended?):
 
```
open FSharp.Data
let payload = [ for i=0 to 701 do yield "<div>" ] |> String.concat ""
let page = HtmlDocument.Parse payload
```
```
Process is terminated due to StackOverflowException.
Session termination detected. Press Enter to restart.
```

**Comment by xenocons** [comment]
I did a git clone and rebuilt and the problem went away.

**Comment by colinbull** [comment]
Actually just looking at this there is a problem with [`HtmlParser.fs`](https://github.com/fsharp/FSharp.Data/blob/master/src/Html/HtmlParser.fs#L664) since it is not tail recursive heavily nested tags will blow the stack.
