### ISSUE TITLE
Xml provider loose pluralized parent in depth

### ISSUE THREAD

**Issue by cboudereau** [fsharp/FSharp.Data#793]
Given :
`<root><items><item><text>hello</text></item><item><text>world</text></item></items><root>`
When: I use type provided and use their infered constructor (not with XElement parameter) for serialiazing purpose and I write a unit test to compare Xml with the given sample
Then : The pluralized parent items is repeated foreach child instead to keep it. When I remove text node all works fine, maybe depth problems.

**Comment by cboudereau** [comment]
With this sample because github skip my sample<root><items><item><text>hello</text></item><item><text>world</text></item></items><root>

**Comment by cboudereau** [comment]
With this sample because github skip my sample
<root><items><item><text>hello</text></item><item><text>world</text></item></items><root>

**Comment by cboudereau** [comment]
With this sample because github skip my sample
(root)(items)(item)(text)hello(/text)(/item)(item)(text)world(/text)(/item)(/items)(root)

Replace parenthesis by node

**Comment by pver** [comment]
I can confirm this issue, if you have this in the example xml:
```
<translations>
        <translation language='nl'>some text</translation>
        <translation language='en'>more text</translation>
</translations>
```
the type provider generates a Translation [] for this. When deserializing, everything is OK.
But when you serialize the corresponding XElements for such a Translation[], this results in:
```
<translations>
        <translation language='nl'>some text</translation>
</translations>
<translations>
        <translation language='en'>more text</translation>
</translations>
```

**Comment by ovatsus** [comment]
Is this the right repro? https://github.com/ovatsus/FSharp.Data/commit/ea5f696bffe8efd438f390bd6697312a70704e3e
It's working for me as expected

**Comment by cboudereau** [comment]
Could you send us your expected result

**Comment by ovatsus** [comment]
The expected result is there on the test:

    "<translations><translation language=\"nl\">some text</translation><translation language=\"en\">more text</translation></translations>"

There's just one outer translations elements, not two

**Comment by cboudereau** [comment]
Thank you. What is the value of the xmlprovider parameters?

**Comment by pver** [comment]
@ovatsus I tried it with your test and that test works fine indeed. But I can reproduce the issue as soon as I add a root element, so that the 'translations' element is no longer the root of the sample.

If you change to test to this:
```
type TranslationsTP = XmlProvider<"""<root><translations>
        <translation language='nl'>some text</translation>
        <translation language='en'>more text</translation>
</translations></root>""">
type TranslationsTP = XmlProvider<"""<root><translations>
        <translation language='nl'>some text</translation>
        <translation language='en'>more text</translation>
</translations></root>""">

[<Test>]
let ``Serializing arrays do not introduce multiple outer tags``() =
    let xmlTranslations = [| TranslationsTP.Translation("nl", "some text"); TranslationsTP.Translation("en", "more text") |]
    let xmlRoot = TranslationsTP.Root(xmlTranslations)
    let serializeResult = xmlRoot.XElement.ToString(SaveOptions.DisableFormatting)
    serializeResult |> should equal "<root><translations><translation language=\"nl\">some text</translation><translation language=\"en\">more text</translation></translations></root>"
```
the test fails, and you can see that serializeResult has this xml string:
```
<root>
  <translations>
    <translation language="nl">some text</translation>
  </translations>
  <translations>
    <translation language="en">more text</translation>
  </translations>
</root>
```
(I've added some formatting to make the result xml more clear)

Also I noticed that with this new xml sample, you no longer have a 'TranslationsTP.Translations' type being generated, only a 'TranslationsTP.Translation' (but the Root type accepts a 'TranslationsTP.Translation[]' array). Maybe that's part of the problem?

**Comment by ovatsus** [comment]
This is the signature without the outer root element:

![image](https://cloud.githubusercontent.com/assets/738761/6769395/48e191ba-d091-11e4-9b57-d2d163efef1f.png)

This is the signature with the outer root element:

![image](https://cloud.githubusercontent.com/assets/738761/6769391/3b8b7594-d091-11e4-831c-d1b6cbd284f8.png)

I need to modify CreateRecord so in that "translations|translation" case it unfolds the inner elements which were created recursively

**Comment by pver** [comment]
Great, thanks @ovatsus :+1:

**Comment by cboudereau** [comment]
Thank you!
