### ISSUE TITLE
[XML] Using recursive elements and SampleIsList=true and Global=true crashes VS

### ISSUE THREAD

**Issue by pver** [fsharp/FSharp.Data#795]
I was trying to use the Global=true and SampleIsList=true for a sample xml using recursive elements. This seems to crash visual studio. I could reproduce it using the example to parse div's from the documentation pages (I duplicated the example to have a sample list) : 
```
type DivProvider = XmlProvider<"""
<test>
<div id="root">
  <span>Main text</span>
  <div id="first">
    <div>Second text</div>
  </div>
</div>
<div id="root">
  <span>Main text</span>
  <div id="first">
    <div>Second text</div>
  </div>
</div>
</test>
 """, SampleIsList=true, Global=true>
```
This only seems to happen when setting both SampleIsList and Global to true. When only setting one of them to true:
`type DivProvider = XmlProvider<""" ... """, SampleIsList=false, Global=true>`
or
`type DivProvider = XmlProvider<""" ... """, SampleIsList=true, Global=false>`
everything seems to work fine (except that it's not reflecting the xml structure I would like to parse).

Should this kind of example work? Or am I using the provider wrong? I'll see if I can get a stacktrace from the crash.

I tested this with VS 2012 Update 4, F# 3.0 and the nuget package of FSharp.Data (v 2.1.1, for target framework .Net 4.5)

**Comment by pver** [comment]
Small update: running it in fsi shows fsi crashes with the following message:
> Process is terminated due to StackOverflowException.

It looks like the type provider gets in a loop somewhere because of the same recursive items across  multiple samples. I'll see if I can further narrow down where this goes wrong

**Comment by ovatsus** [comment]
I tested this on VS 2013 Update 4 with F# 3.1.2 on latest master and couldn't repro. @tpetricek did a recent change on this code, so it might have fixed it: https://github.com/fsharp/FSharp.Data/commit/c3b609ff2ab06b8e1fbe04ed9912b4a6b1611cae
I'll try to release version 2.2.0 soon

**Comment by pver** [comment]
Sounds great, thanks! I'll test it with the new version when it's available and post feedback here
