### ISSUE TITLE
JSON library doesn't share types

### ISSUE THREAD

**Issue by plinth666** [fsharp/FSharp.Data#796]
Given two a hierarchy of JSON provided types, there is no obvious way to present sub members as "already having been provided." so that the code and types can be shared.

Example of what might work

    type FooProvider = JsonProvider<fooExampleJson>
    type BarProvider = JsonProvider<barExampleJson, ["foo", FooProvider]> // list of tuples mapping to existing types.

**Comment by ovatsus** [comment]
That is something not supported by the TP language feature, unfortunately
