### ISSUE TITLE
JSON provider load methods have implicit rather than explicit control over the Method used.

### ISSUE THREAD

**Issue by plinth666** [fsharp/FSharp.Data#797]
If a Load() needs to happen such that it induces a POST, there is no direct way to do that without interjecting a function callback to mutate the HttpWebRequest (or by putting in a body, which forces POST).

While the callback is a workaround and it is understood that the Http object is a light-duty object, this is a sharp edge that could easily be filed down for a common case.

**Comment by ovatsus** [comment]
Could you clarify? I'm not sure I understand what you're requesting

**Comment by plinth666** [comment]
If I call the Load() method, it will implicity induce a http GET unless there is a body, whereby it will implicity induce a POST. There should be a way to *explicitly* cause an http GET, POST, PUT, DELETE etc without having to depend on implicit functionality.

Currently, the only way to do this is to use the flavor of Load with a callback to mutate the http object: inconvenient, ugly. Allowing the explicit specification of the http mechanism is common and convenient.

**Comment by ovatsus** [comment]
What do you mean by callback? There's only one .Load method generated for JsonProvider, and it always assumes GET.

**Comment by plinth666** [comment]
And that's exactly the problem.  If I want to do anything else (which is common), I have to do this:
let httpPost url = Http.RequestString(url, customizeHttpRequest=(fun req -> req.Method <- "POST"; req))

let resp = httpPost uri
let myJson = SomeProvider.Parse(resp)

Why can't I do
let myJson = SomeProvider.Load(uri, "POST")
or better still
type HttpRequestMethod = Get|Post|Delete|Put // etc
let myJson = SomeProvider.Load(uri, Post)

**Comment by ovatsus** [comment]
You can do this:

    let resp = Http.RequestString(url, httpMethod = HttpMethod.Post)
    let myJson = SomeProvider.Parse(resp)

Which is simple enough, I think
It would be a bit messy to support all of the params of Http.RequestString on the Load methods of TPs so we only support the more common case
