### ISSUE TITLE
JSON type provider should support typing

### ISSUE THREAD

**Issue by plinth666** [fsharp/FSharp.Data#798]
While I understand that the JSON standard is weakly typed at best, the resulting types are usually string. I would like to have a meta-schema (since JSON is not allowed to have comments) used to create the type provider that lets me have strong types for the elements so that in addition to having names on values, I can also require that elements have specific types or require their existence or their optionality.

So if my schema says that field foo is "int required", the prop is an int. If my schema says, "bool optional", I get a bool option for the type and a bubbled up exception or a handling mechanism when there is an issue.

This would probably also require data projectors for unusual representations.

**Comment by jruizaranguren** [comment]
There is a related idea which coud be used to allow for a more "typed" approach: https://github.com/fsharp/FSharp.Data/issues/677

**Comment by ovatsus** [comment]
Closing as dup of #677
