### ISSUE TITLE
Closing tag with number breaks document parsing for Html provider 

### ISSUE THREAD

**Issue by vlasenkoalexey** [fsharp/FSharp.Data#800]
Here is perfectly valid html:
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;Title&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;a href="www.google.com"&gt;0&lt;/a&gt;
    &lt;script type="text/javascript"&gt;
        var a = '&lt;/1&gt;'
    &lt;/script&gt;
    &lt;a href="www.google.com"&gt;1&lt;/a&gt;
    &lt;a href="www.google.com"&gt;2&lt;/a&gt;
    &lt;a href="www.google.com"&gt;3&lt;/a&gt;
&lt;/body&gt;
&lt;/html&gt;

When I'm trying to load and parse it only first link is returned:
let data = ...HtmlProvider.Load(stringreader)
let allLinks = data.Html.Descendants["a"] |> Seq.toList

If &lt;/1&gt; is removed or replaced by some tag not containing numbers parsing works as expected.

**Comment by colinbull** [comment]
This is fixed in PR #799
