### ISSUE TITLE
How to change the time-out value of request in HTTP Utilities

### ISSUE THREAD

**Issue by darting** [fsharp/FSharp.Data#802]
Hi all, 

how can I change the time-out value of request? I can not find any documentation. 

thank you very much

**Comment by colinbull** [comment]
Do you mean on a `Http.AsyncRequest` variant or on one of the type providers?

If it is on the `Http.AsyncRequest` variants then there is an optional parameter `customizeHttpRequest` that takes a function in which you can set the timeout, for example, 

      Http.AsyncRequest("http://www.google.com", 
                                      ?customiseHttpRequest = (fun req -> req.Timeout <- 1000; req)

If it is on a the type provider then it is not exposed in the static parameters. However you can do something like the following, 

     type Data = CsvProvider<"sample.csv">

     let data  = Data.Load(Http.RequestStream("http://some/uri", 
                                          ?customiseHttpRequest = (fun req -> req.Timeout <- 1000; req)
                                          ))

Hope that helps

**Comment by darting** [comment]
thank you very mush!!!

**Comment by ovatsus** [comment]
This will need custom logic to implement. Marking as up for grabs

**Comment by scrwtp** [comment]
I've set up a PR after this issue cropped up on SO yesterday.

**Comment by eriawan** [comment]
@ovatsus I think this issue should be closed.
It's been fixed by PR #920  from @scrwtp 🙂
