### ISSUE TITLE
Build is failing on appVeyor with a sourcelink error

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#810]

**Comment by ovatsus** [comment]
@ctaggart could you have a look? It's complaining about the FSharp.Data.Portable7.fsproj, but earlier on the script that was built without problems. I think the problem is that the VisualStudio variable is being evaluated incorrectly inside the sourcelink script

**Comment by ctaggart** [comment]
Yes, I'll have a look.

**Comment by ctaggart** [comment]
So i see the latest build failed.
https://ci.appveyor.com/project/ovatsus/fsharp-data

![image](https://cloud.githubusercontent.com/assets/80104/6887103/49c72a72-d609-11e4-81e6-a9e437d2dae9.png)

This got updated:
https://github.com/fsharp/FSharp.Data/blame/master/src/FSharp.Data.Portable7.fsproj#L85

```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.Portable.FSharp.Targets" />
```

See https://github.com/ctaggart/SourceLink/issues/50 for the best solution at the moment.

```
//        let p = VsProj.LoadRelease proj
        let p = VsProj.Load proj ["Configuration","Release"; "VisualStudioVersion","12.0"]
```

**Comment by ovatsus** [comment]
Thanks, I'm trying that

**Comment by ovatsus** [comment]
Problem fixed. Thanks for your help!
