### ISSUE TITLE
Add support to HTTP Utility for multipart/form-data

### ISSUE THREAD

**Issue by tonyj444** [fsharp/FSharp.Data#811]
I have been trying to use the Http Utility to post data to a REST API which requires the upload of both key-value pairs (FormValues) in addition to a byte stream.  As far as I'm aware the only way to achieve this in a single post is to use the multipart/form-data content-type as detailed here:  http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

It looks as though this would be best achieved by expanding the HttpRequestBody DU.  Does this sound like the most sensible approach and would there be interest in this feature?

**Comment by ovatsus** [comment]
Sure, go for it

**Comment by ovatsus** [comment]
I see that you did some work already on this, is it almost ready?

**Comment by tonyj444** [comment]
My code works but with two known limitations:
1) No support for byte streams submitted as a single form value (i.e. a file-selector that allows multiple files)
2) Will fail if the a ContentType has been specified

The first I am aiming to resolve this weekend.

The second I'm not totally sure what to do - for multipart forms the ContentType MUST be multipart/form-data.  If the user has set their own ContentType should we just overwrite it?  Or throw?

**Comment by ovatsus** [comment]
For 2 I'd prefer to throw

**Comment by ovatsus** [comment]
@tonyj444, still interested in sending a PR for this?

**Comment by ovatsus** [comment]
This was already done
