### ISSUE TITLE
Data transformation before type generation

### ISSUE THREAD

**Issue by nickbabcock** [fsharp/FSharp.Data#812]
Problem: Say you are dealing with the following Json, which for better or
worse, you don't control:

```json
{
  "countries": {
    "HAB": {
      "small": true,
      "treasury": 10.000
    },
    "FRA": {
      "small": false
    }
  }
}
```

In Json provider's current state, `HAB` and `FRA` will be detected as different types (appropriately so), but that is not desired. Let's say it is a design flaw of the API where the keys under `countries` are dynamic, such that from document to document the *list* varies, so the sample is useless (and by extension the type provider). `countries` should not be an object, it should be an array! How can we achieve this goal?

A potential solution is add one argument to the type provider, such that there is a transformation of the `JsonValue` before type generation.

Such transformation could result in the type generation from the equivalent Json.

```json
{
  "countries": [{
    "abbreviation": "HAB",
    "small": true,
    "treasury": 10.000
  }, {
    "abbreviation": "FRA",
    "small": false
  }]
}
```

And then the type provider works swimmingly! Anyways, I felt like this was an interesting problem and I wanted to pose it to everyone here. Is something like this even possible from a type provider technical standpoint?

**Comment by ovatsus** [comment]
It's not possible to do that at compile time, the inputs to TPs are very limited, but on a fsx script, you can download the json, transform it, save it to an intermediate file, and then use that intermediate file on the TP. I do that a lot of times. The only downside is that you cannot simply evaluate the entire script at once, but if you do it piece by piece, it works fine

**Comment by nickbabcock** [comment]
Ok, thanks for the response. It's less than optimal because the JSON being worked with is relatively large ~60MB, and I would prefer only a single pass through, but a limitation is a limitation!

Feel free to close this issue because it seems like this issue can't be solved.
