### ISSUE TITLE
[HTML provider] Problems with emails

### ISSUE THREAD

**Issue by Seanseviltwin** [fsharp/FSharp.Data#817]
I think it's caused by the mailto attribute or the @ or :+1: symbol inside it. When you try to get the inner text of an "a" tag with a mailto attribute, you get incomprehensible gibberish.
Going to give fixing this a go.

**Comment by Seanseviltwin** [comment]
Okay, so it works when I download the html before running the app rather than loading it from the internet directly, so I'm thinking maybe it's something to do with encoding.

**Comment by Seanseviltwin** [comment]
Also thanks ovatsus.

**Comment by ovatsus** [comment]
Maybe the issue might be on the Http module that is screwing up the encoding and not in the html parser itself?

**Comment by Seanseviltwin** [comment]
Yeah, was looking at that but was finding the code hard to read. I'm trying to see if I can pull down the text of the page myself and find out the correct encoding, then going back and seeing what's wrong.

**Comment by ovatsus** [comment]
Closing as there's no repro
