### ISSUE TITLE
Do not run SourceLink step on CI when from a pull request

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#826]

**Comment by ovatsus** [comment]
@ctaggart any idea how to do this? On AppVeyor pull requests always fail with a checksum error, but not sure how to detect if running from master or from a pull request

**Comment by ctaggart** [comment]
Sure, I'll take a look.

**Comment by ovatsus** [comment]
Thanks

**Comment by ctaggart** [comment]
Do you have an example pull request build that I can look at? I'm looking through the list here:
https://ci.appveyor.com/project/ovatsus/fsharp-data/history

**Comment by ovatsus** [comment]
https://ci.appveyor.com/project/ovatsus/fsharp-data/build/2.2.1-a1505011909

>source linking C:\projects\fsharp-data\src\bin\Release\FSharp.Data.DesignTime.pdb 
2 source files do not have matching checksums in the git repository 
no checksum match found for C:\projects\fsharp-data\paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\DebugProvidedTypes.fs 
no checksum match found for C:\projects\fsharp-data\paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fs 
Running build failed.
Error:
System.Exception: 2 source files do not have matching checksums in the git repository
   at FSI_0001.SourceLink.GitRepo.VerifyChecksums(GitRepo x, IEnumerable`1 files) in C:\projects\fsharp-data\packages\SourceLink.Fake\tools\SourceLink.fsx:line 47
   at FSI_0001.Build.clo@156-17.Invoke(Unit unitVar0) in C:\projects\fsharp-data\build.fsx:line 162
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411

**Comment by ctaggart** [comment]
You don't need to disable source indexing on pull requests. You need to exclude the `paket-files` that are downloaded by paket and are not in your git repository.
https://github.com/ctaggart/SourceLink/issues/45

**Comment by ctaggart** [comment]
It would actually be a good idea to have those two files be source indexed. In that case, you need to commit them to your repo. I think you can have paket put them in another folder if that helps.

**Comment by ovatsus** [comment]
Ah, thanks!
