### ISSUE TITLE
Who can help me turn code that reads SAS files into a TypeProvider?

### ISSUE THREAD

**Issue by gjvdkamp** [fsharp/FSharp.Data#831]
Hi all, 

A while ago I wrote some code that can natively read SAS files (without having to have any SAS software on your computer). If you work in finance, risk, statistics etc SAS is used quite a lot. I used [Matt Shotwell](http://biostatmatt.com/uploads/shotwell-sas7bdat-useR-2011.pdf)'s description of the file format. 

If reads the metadata and generates code that then reads the files. My original idea was to write a TypeProvider but that has remained elusive. I can imagine this would be walk in the park for most of you. If any of you is interested I can send/pull the code and we can team up to open up SAS to F#. 

Gert-Jan

**Comment by tpetricek** [comment]
Hi,
I have not used SAS myself (and have no access to it), but I heard it mentioned by some people - so if you have some code that you are happy to share, it would definitely be a great thing to do!

We setup the "F# Data Toolbox" project as a home for things that might be useful, but are not quite as main-stream (and as tested) as code in F# Data: http://fsprojects.github.io/FSharp.Data.Toolbox/ So, it sounds like sending a PR there might be a great way to make the code available...

Thanks!

**Comment by gjvdkamp** [comment]
Hi Tomas, 

Ok will go to Toolbox with it. I just checked the code for the first time after a while and it turned out to be a little messier than I could remember (or I need to find the latest version again). I'll clean it up to make anyone else's life easier, figure out this Git (only used svn so far) and follow up asap.

**Comment by ovatsus** [comment]
This is now in the toolbox, so closing this issue
