### ISSUE TITLE
Loading FSharp.Data dll in fsi creates DesignTimeURIs & WorldBankSchema directories in working dir

### ISSUE THREAD

**Issue by obadz** [fsharp/FSharp.Data#833]
Simply running

```
fsi -r:FSharp.Data.dll
```

Creates those directories with one file in each. Is there anything we can do to avoid this?

(I'm running on Linux so not sure if that behavior is Linux-specific)

```
$ ls -R
DesignTimeURIs/:
0CdPVqScGxbsHluW0KvuHpKSPow%3D.txt

WorldBankSchema/:
0CdPVqScGxbsHluW0KvuHpKSPow%3D.txt
```

**Comment by ovatsus** [comment]
Those dirs are supposed to be created on Environment.GetFolderPath(Environment.SpecialFolder.InternetCache)

**Comment by obadz** [comment]
Quite possible:

```
> System.Environment.GetFolderPath(System.Environment.SpecialFolder.InternetCache);;
val it : string = ""
```

mono-4.0.1/mcs/class/corlib/System/Environment.cs has:

```csharp
            case SpecialFolder.InternetCache:
                if (Platform == PlatformID.MacOSX)
                    return Path.Combine (home, "Library", "Caches");
                else
                    return String.Empty;
```

Guess I have to patch Mono

**Comment by ovatsus** [comment]
A pull request to workaround this would be welcomed

**Comment by obadz** [comment]
Pull request sent.

As an aside, is it desirable behavior for a DLL to go over the network, download some stuff, and save some files, just because it was referenced? Shouldn't that be the result of more explicit actions by the developer, such as a function call?

**Comment by ovatsus** [comment]
In type providers that's normal, as the data has to be fetched at compile time.
Thanks for the pull request, I'll have a look at it later

**Comment by obadz** [comment]
Thought the type provider stuff was in the DesignTime dll

**Comment by ovatsus** [comment]
When you reference FSharp.Data.dll, the type providers in DesignTime dll are automatically loaded, you never reference the DesignTime dll
