### ISSUE TITLE
Any plans to support modern .Net 4.5 pcl profiles?

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FSharp.Data#839]
The following two profiles seems to be extensively used and now supported by F#:
profile78 =  portable-net45+netcore45+wp8
profile259 = portable-net45+netcore45+wpa81+wp8

**Comment by ovatsus** [comment]
Yep, see https://github.com/fsharp/FSharp.Data/pull/672. Unfortunately I'm stuck on that, as the modern profiles of mscorlib into system.runtime and others causes lots of issues :(
