### ISSUE TITLE
JsonProvider Error on Mono

### ISSUE THREAD

**Issue by jeremyabbott** [fsharp/FSharp.Data#843]
When passing a URL to JsonProvider as a JSON sample I receive the following error: "Error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error: Object reference not set to an instance of an object"

For example, this bombs: 

```fsharp
type Issue = JsonProvider<"https://api.github.com/repos/fsharp/FSharp.Data/issues">
```

However, this is acceptable:

```fsharp
type Simple = JsonProvider<""" { "name":"John", "age":94 } """>
```

The issue only appears to happen on Mono (version 4.0.1) using Xamarin Studio. The same code works fine in Visual Studio on Windows. 

I'm happy to help provide a fix with some guidance.

**Comment by jeremyabbott** [comment]
I pushed a sample repo as a reference. https://github.com/jeremyabbott/fsharpdata

**Comment by ovatsus** [comment]
This is probably https://github.com/fsharp/FSharp.Data/issues/823 which was just fixed. I'll publish a new version to NuGet soon
