### ISSUE TITLE
F# interactive error: TypeProviderAssemblyAttribute refers to FSharp.Data.DesignTime

### ISSUE THREAD

**Issue by iainnicol** [fsharp/FSharp.Data#844]
Create a new F# project and add FSharp.Data from Nuget.

Next, create an fsx script:

```
#I "bin/Debug"
#r "FSharp.Data.dll"
open FSharp.Data.CsvExtensions

module Main =
    let main () = ()
Main.main ()
```

Send the script to the F# interactive window (using alt+enter).  Then you get the following error message:

`Script1.fsx(2,1): error FS3031: The type provider 'C:\Users\Foo\Documents\Visual Studio 2015\Projects\fsharpdata\fsharpdata\bin/Debug\FSharp.Data.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'file:///C:\Users\Foo\Documents\Visual Studio 2015\Projects\fsharpdata\fsharpdata\bin\Debug\FSharp.Data.DesignTime.dll' or one of its dependencies. The system cannot find the file specified.`

Weirdly, this error doesn't happen if you send the script to the F# interactive window again.

**Comment by franssu** [comment]
I was trying to reference bin/Debug/FSharp.Data.dll from a .fsx, got the same error. So I referenced it from the Nuget package, i.e. "../packages/FSharp.Data.2.2.5/lib/net40/FSharp.Data.dll" in my case, and the error's gone (because this directory contains FSharp.Data.DesignTime.dll)

**Comment by ExoltenOne** [comment]
I had the same when I copied project with FSharp.Data installed via NuGet. A reinstallation FSharp.Data on this project via NuGet helped.
