### ISSUE TITLE
HTML Type Provider fails with "more than one nested type"

### ISSUE THREAD

**Issue by ptrelford** [fsharp/FSharp.Data#849]
I'm trying to use the HTML type provider over the the Dr Who page on Wikipedia:

    type who = FSharp.Data.HtmlProvider<"http://en.wikipedia.org/wiki/Doctor_Who">

When I type `who` dot I get a note saying "There is more than one nested type called 'ReferenceWebsites'".

**Comment by colinbull** [comment]
Looks like I have missed a use of the unique name generator somewhere. I'll look into this over the weekend.

-----Original Message-----

**Comment by colinbull** [comment]
Is this on the nuget package or from source?

**Comment by ptrelford** [comment]
Sorry, forgot to mention that, it was from the Nuget package, version 2.2.3

**Comment by ovatsus** [comment]
There's a table and list wit the same name, fixing. Also found that the list values weren't correct when there are links
