### ISSUE TITLE
SourceLink failing on TypeProviderStarterPack files

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#851]
https://ci.appveyor.com/project/ovatsus/fsharp-data/build/2.2.4-a1506292101

**Comment by ctaggart** [comment]
![image](https://cloud.githubusercontent.com/assets/80104/8419062/f9f91f2c-1e6b-11e5-8a69-9960875cef31.png)

`paket-files` are not in the repository. You need to them. I'm working on a `0.6` release that should be out this week. I'll create a PR for this.

**Comment by ovatsus** [comment]
Failing again on current master:

![image](https://cloud.githubusercontent.com/assets/738761/14942544/cd8754c0-0fb7-11e6-8448-acdf48597f2d.png)
