### ISSUE TITLE
get_OSVersion in Windows 8.1 app 

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Data#858]
From [a comment on Channel 9](https://channel9.msdn.com/Blogs/Seth-Juarez/Type-Providers-in-F-with-Tomas-Petricek)

> I can't seem to get FSharp.Data to work in my Windows 8.1 app. I added an F# portable library to the solution and when I use Http.AsyncRequestString, I get a System.InvalidOperationException: The API 'System.Environment.get_OSVersion()' cannot be used on the current platform.

**Comment by ovatsus** [comment]
There's bigger issues than that unfortunately. Without any of the 3 new-style pcl profiles working, many things don't word. Profile 47 crashes at runtime all over :/

**Comment by ovatsus** [comment]
I tried create a Windows 8.1 app that calls Http.AsyncRequestString and it seemed to be working fine, though I have Windows 10 installed, so might not exactly be the same. In any case sent PR with potential fix
