### ISSUE TITLE
How to get only inner text from an HtmlNode?

### ISSUE THREAD

**Issue by xperiandri** [fsharp/FSharp.Data#861]
I have such HTML
```HTML
<div class="matchheader">
    <div class="whenm">
        21 minutes ago
        <span style="color: rgb(114, 163, 38); font-weight: bold; text-shadow: 1px 1px 0px #4a7010;"> LIVE</span>
        <span style="color: rgb(209, 33, 33); font-weight: bold;">&nbsp;&nbsp;</span>
    </div>
    <div class="eventm">Do Gaming League</div>
</div>
```
And I want to extract ```21 minutes ago``` from it.
But ```InnerText()``` returns ```21 minutes ago LIVEÂ Â "``` instead.

How to eliminate span elements from inner text?

**Comment by ovatsus** [comment]
This is a gap, this should be fixed. As a immediate workaround you can use ``HtmlNode.innerTextExcluding ["span"] div``

**Comment by xperiandri** [comment]
Cool! Thanks, this indeed works!
