### ISSUE TITLE
Json Parser ambiguousness when parsing numbers using cultures

### ISSUE THREAD

**Issue by mrange** [fsharp/FSharp.Data#863]
As the json parser supports parsing numbers according to the current culture what is the reasonable behavior of the following code (swedish culture uses ',' as decimal delimiter)?

```
let j = JsonValue.Parse("[25,5,5,25]", CultureInfo.GetCultureInfo "sv-SE")
```

It seems to crash currently but I am unsure what would make sense.

The following code also seems to crash:

```
let j = JsonValue.Parse("{ \"age\": 25,5, \"id\":0}", CultureInfo.GetCultureInfo "sv-SE")
```

If one goes by the letter of the law (json.org) the answer seems easy (don't support cultures) but in reality removing features are always hard.

**Comment by ovatsus** [comment]
The default is the invariant culture, so that works ok, if a culture is specified with comma as the decimal separator, I'd say comma being the array delimited should take precedence.

**Comment by mrange** [comment]
What do you mean by take precedence? Should [1,2,3] be interpreted as:
[1,2,3]
[1.2,3]
or 
[1,2.3]

**Comment by ovatsus** [comment]
The first one. I haven't double checked, but I believe that's the current behaviour. If not, I would consider that a bug, as it would be deviating from the json spec

**Comment by mrange** [comment]
When trying to add a test case this seems to crash:

```
[<Test>]
[<SetCulture("sv-SE")>]
let ``Can parse floats in swedish cultures``() =
    let j = JsonValue.Parse("[1,2,3]", CultureInfo.CurrentCulture)
    j.[0].AsFloat(CultureInfo.CurrentCulture) |> should equal 1
    j.[1].AsFloat(CultureInfo.CurrentCulture) |> should equal 2
    j.[1].AsFloat(CultureInfo.CurrentCulture) |> should equal 3
```

**Comment by mrange** [comment]
I suspect it's because parseNum tries to parse `1,2,3` as float

```
    and parseNum() =
        let start = i
        while i < s.Length && isNumChar(s.[i]) do
            i <- i + 1
        let len = i - start
        match TextConversions.AsDecimal cultureInfo (s.Substring(start,len)) with
        | Some x -> JsonValue.Number x
        | _ ->
            match TextConversions.AsFloat [| |] (*useNoneForMissingValues*)false cultureInfo (s.Substring(start,len)) with
            | Some x -> JsonValue.Float x
            | _ -> throw()
```
