### ISSUE TITLE
XmlProvider in 2.2.5 on F# 4 project causes multiple FSharp.Core assembly references

### ISSUE THREAD

**Issue by marklam** [fsharp/FSharp.Data#867]
To repro:
Create an empty F# 4 Console app in VS2015
Add the FSharp.Data 2.2.5 package
Use an Xml provided class:
```
type FooXml = FSharp.Data.XmlProvider<"""<Root><Node><SubNode/></Node></Root>""">

[<EntryPoint>]
let main _argv = 
    FooXml.Load(@"c:\temp\foo.xml").XElement.Attributes() |> Seq.length
```
Look at the Assembly references for the exe under ILSpy
```
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// FSharp.Data, Version=2.2.5.0, Culture=neutral, PublicKeyToken=null
// FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
```
There are duplicate identical mscorlib references; and references to FSharp.Core 4.3.1 and 4.4.0

**Comment by ovatsus** [comment]
/cc @dsyme 
Not sure how to fix this, I think it's a generalized problem with type providers

**Comment by cboudereau** [comment]
With vs 2015, fsharp.core came from framework with the project node private
true. Nuget can't understand the problem with the target framework nuget
config. I think for fsharp 4 type provider must have the fsharp.core from
framework not from nuget.

**Comment by dsyme** [comment]
I just took a look at this.  If it helps, I don't think it's actually a problem as long as an appropriate binding redirect for FSharp.Core is present for the execution of the overall program.  

The way FSharp.Data works currently is that it emits either FSharp.Core 4.3.0.0 (when using ``lib\net40\FSharp.Data.dll``) or FSharp.Core 2.3.5.0 (when using ``lib\portable-net40+sl5+wp8+win8\FSharp.Data.dll``) references.  When using a binding redirect at runtime these are redirected appropriately, e.g. using a ``foo.exe.config`` containing

``
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
``

Ideally FSharp.Data would be able to normalize the emitted references it passes back to the F# compiler to the FSharp.Core and mscorlib being targeted in the current compilation.  However, as pointed out by Kevin Ransom, the F# compiler infrastructure doesn't currently make this easy.  Short of a consistent, simple and robust way of doing that, it's probably better to just emit them as is currently being done.  The IL is still valid.  However it may be a good idea to document that a binding redirect will _definitely_ be needed (if you haven't documented that already).

**Comment by ovatsus** [comment]
@dsyme, do you know if your multi-targeting changes fixed this?
