### ISSUE TITLE
Single column CSV Row construction gets invalid cast to 1-tuple.

### ISSUE THREAD

**Issue by philderbeast** [fsharp/FSharp.Data#870]
With FSharp.Data v2.2.0 and v2.2.5 I got this exception when constructing single column CSV rows. I had no such problem with multicolumn CSV rows.

    type S = CsvProvider<"""
    s (string)
    aa
    bb
    """>

    ["aa"; "bb"] |> List.map (fun x -> S.Row(x))
    // System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Tuple`1[System.String]'.

I get the same error with ...

    ["aa"; "bb"] |> List.map (fun x -> S.Row x)

**Comment by philderbeast** [comment]
A workaround is to use a dummy 2nd column ...

    type S = CsvProvider<"""
    s (string), dummy (string option)
    aa,
    bb,
    """

    ["aa"; "bb"] |> List.map (fun x -> S.Row(x, None))

**Comment by ovatsus** [comment]
This won't be easy to fix, and it doesn't seem a very common scenario. Not sure if we should just throw a mote explicit exception like "one column csv's not supported
