### ISSUE TITLE
Up for grabs: Add encoding parameter to load methods of CSV/XML/CSV provider

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FSharp.Data#871]
Pretty sure the problem referenced in this Gist https://gist.github.com/mitalkakaiya/18bc73acd69cee514a1c is because `StreamReader :> TextReader` constructed at line 227 in FSharp.Data.IO is always constructed with `Encoding.UTF8`. The reader skips big blocks of rows in the input file, starting after successfully reading line 10470 in the input file. 

Does not seem to be a way for user to pass alternate character encoding.

**Comment by ovatsus** [comment]
You can always use the overload that takes a stream instead, but agreed, this should be fixed

**Comment by jackfoxy** [comment]
I'm only guessing the issue is with the encoding. All I know for sure is the TextReader skipping blocks of lines according to breakpoints I set in `CsvRuntime.fs let rec readLines lineNumber = seq {...`

**Comment by ovatsus** [comment]
This might be the same as https://github.com/fsharp/FSharp.Data/issues/891
