### ISSUE TITLE
XmlProvider throws up

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsharp/FSharp.Data#874]
When pointed at a large complex Xml file intellisense dies, autocomplete dies, the VisualStudio stops responding, and sometimes compilation just stops working with 
![image](https://cloud.githubusercontent.com/assets/121276/9860688/9fb88792-5afb-11e5-9453-d3edf2bc896d.png)

after trying to build, which never finishes it then switches to
`The type provider 'ProviderImplementation.XmlProvider' reported an error: Cannot resolve dependency to assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.`

![image](https://cloud.githubusercontent.com/assets/121276/9861027/c9962bf8-5afd-11e5-85f1-4edb43373d5c.png)

I'm trying in the latest attempt to make a smaller sample string, instead of using the file itself as the type provider generation target.

System.Xml is referenced from `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll`

The target file is an 8Mb xml file from ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Publications/ICD10CM/2015/ICD10CM_FY2015_Full_XML.zip

the entire code file is

```
namespace Foo //Icd10LoadWithGems
open System
open FSharp.Data

module Helpers = 
    let delimit delimiter (values:string seq) = String.Join(delimiter,values)
    let replace (item:string) replace (s:string) = s.Replace(item,replace)
    let combine basePath path = System.IO.Path.Combine(basePath,path)
    let wrap wrapper s = wrapper + s + wrapper
    let wrap2 left right s = left + s + right
open Helpers

// not needed on current serialization path: [<CLIMutable>]
type Diagnosis = {Code:string;Desc:string}

type Template = {Id:string}
type Diagnosis' = {IcdCode:string;Diagnosis:string; ShortDescription:string;LongDescription:string; FullTextSearch:string;Templates:Template list}
type Diagnoses = {Diagnosis: Diagnosis' list}
type Column = {Name:string;IsMatch:bool}
//[<NoComparison>]
//type TableSpecifier = {TableName:string; HasIdentity:bool; Columns: Column seq; Values: string seq seq;}
module GemLoader = 
    [<Literal>]
    let drugPath = @"C:\ICD10CM_FY2015_Full_XML\FY15_Tabular.xml"

// this is the code before I switched it to using the local sample string
type Icd10 = XmlProvider<GemLoader.drugPath, Global=true >
//...
```

**Comment by ovatsus** [comment]
It's a bit slow, but with current master works correctly (probably because of the changes to the assembly loader)
Will leave this here anyway as a good example to run a profiler on and try to optimize

**Comment by ovatsus** [comment]
Can you try if this is better with 2.3.0 which was released today? There was a bunch of changes in the assembly loader, including a memory leek which was fixed

**Comment by Thorium** [comment]
#976 can help a little but still I'm bit worried that Visual Studio uses a lot of memory that is not released.

**Comment by baronfel** [comment]
Another sample file for testing: https://webgate.ec.europa.eu/europeaid/fsd/fsf/public/files/dtdFullSanctionsList/content?token=dG9rZW4tMjAxNw

**Comment by ovatsus** [comment]
Please try again with 3.0 beta 2
