### ISSUE TITLE
Bug when call request from Http module

### ISSUE THREAD

**Issue by flypixel** [fsharp/FSharp.Data#879]
```fsharp
[<LiteralAttribute>]
let url = "http://www.staples.com/"
let custom (req: System.Net.HttpWebRequest) = 
    req.Proxy <- new System.Net.WebProxy("http://XXX.XXX.XXX.XXX:8889")
    req
let page = Http.RequestString(url=url, customizeHttpRequest=custom)
```
and I get this exception in fsi:
*System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in ...\HttpExperiment.fsx:line 42
Stopped due to error.*
When I use standard *HttpWebRequest* for the same purposes, no exceptions were raised.
P.S. There are sites where this exception wasn't raised in the same situation.

**Comment by flypixel** [comment]
Sorry, it was my miss understanding of situation, every thing works greate, thanks

**Comment by flypixel** [comment]
When I changed code of *custom* function to this:
```fsharp
let custom (req: System.Net.HttpWebRequest) = 
    req.Proxy <- new WebProxy("http://XXX.XXX.XXX.XXX:8889")
    req.Accept <- "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8]"
    req.UserAgent <- "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"
    req.CookieContainer <- cookies
    req
```
It began to work some times. For example for one reques it can be done correctly, but for the next request it can throw the exception  again.

**Comment by ovatsus** [comment]
Cannot repro
