### ISSUE TITLE
Allow user specified Header used to download content

### ISSUE THREAD

**Issue by fairjm** [fsharp/FSharp.Data#880]
http://stackoverflow.com/questions/33010648/jsonprovider-failed-to-parse-json-from-api-written-myself/33057597#33057597  

It's not a bug of `JsonProvider` but a server site bug.  
  
But I think to allow user specified header makes it more compatible to the given corner case.Since not every site is well designed and some of them may break the rule.

**Comment by ovatsus** [comment]
You can specify headers using Http.RequestString and then using the output of that into JsonProvider

**Comment by fairjm** [comment]
You are right.I can do downloading myself.  
Thx.
