### ISSUE TITLE
Xamarin.iOS/Monotouch: Error MT2002: Failed to resolve assembly: 'FSharp.Data, Version=2.2.5.47, Culture=neutral, PublicKeyToken=null' (MT2002) 

### ISSUE THREAD

**Issue by IanLeatherbury** [fsharp/FSharp.Data#888]
When trying to build a Xamarin.iOS project for device that references an F# PCL, I receive the following error:

Error MT2002: Failed to resolve assembly: 'FSharp.Data, Version=2.2.5.47, Culture=neutral, PublicKeyToken=null' (MT2002)

Some preliminary research suggested that I need to build FSharp.Data myself against  Xamarin.iOS, or a supported PCL profile, and that the desktop framework assemblies(either Mono or MS) could not be used.

Is that the trick? If so, could someone shed some light on how to do that? 

@jackfoxy, do you know if your team had to deal with this issue?

[Here](https://github.com/ianleatherbury/tryfsharpforms) is my project, and [here](https://github.com/DavidYKay/HelloFSharpXamarinFormsPCL) is the F# PCL that I'm using.

Thanks!

**Comment by jackfoxy** [comment]
Twitter @tihan may have some ideas.

**Comment by IanLeatherbury** [comment]
I was using an unsupported PCL profile. Re-targeted to PCL Profile 7, which is also supported by Xamarin.Forms, and was able to deploy to device. 

Thank you for the help!
