### ISSUE TITLE
XmlProvider Optionnal types

### ISSUE THREAD

**Issue by Samvrie** [fsharp/FSharp.Data#890]
Hi, I have a question about the XmlProvider about optional types.

I've an element that look like this
``` XML
<Element A="132" B="Ac">
</Element>
```
And I would like to mark the B Element as optional.
To do that in my Sample Xml files I created two *Element*.
``` XML
<Element A="132" B="Ac">
</Element>
<Element A="132">
</Element>
```
With that *Hack* the **XmlProvider** can figure out that the *B Attribute* is actually optional, but when I load an XmlFile it propose me a List of Element, but there's only one in my XmlFile so I access it with 

``` FSharp
Array.get List 0
```
This work but isn't really the result I would like in my code...

Any suggestions?

**Comment by xenocons** [comment]
Hi @Samvrie , perhaps this current proposal will eventually solve this issue, https://github.com/fsharp/FSharp.Data/issues/57 but for now I think your solution is fine as long as you check that the input length contains an element at index 0.

**Comment by Samvrie** [comment]
Yes I an Xsd provider would really simplify the look of my sample XmlFile now. SInce I've a lot of attributes and elements which can be optional...

Thanks for the answer, I will be looking in the XsdProvider if I can give a hand into it.

**Comment by giacomociti** [comment]
Hi @Samvrie, I think you don't need the hack: you can create a file with multiple samples and specify the parameter `SampleIsList = true`. Have a look at the [API reference](http://fsharp.github.io/FSharp.Data/reference/fsharp-data-xmlprovider.html). I cannot find an example in the docs so let me point you to the docs of  [my pet project](http://giacomociti.github.io/AntaniXml/tutorial.html) in the paragraph *Creating samples for the XML type provider*. By the way, if you have a schema, what's shown in this paragraph is a useful hack to create samples automatically, until we get xsd support in F# Data.
