### ISSUE TITLE
Nothing for OleDb?

### ISSUE THREAD

**Issue by gdennie** [fsharp/FSharp.Data#892]
Conventional Sql databases are still important. Having OleDb support with pass through sql would be useful, I think. It would immediately make this library applicable to a vast collection of existing databases.

**Comment by colinbull** [comment]
There are other type providers that handle DB access, to my knowledge the broadest DB type providers are either 

* [EDMX type provider]( 
https://msdn.microsoft.com/en-gb/library/hh362313.aspx) which will basically support anything Entity framework supports. This works via code generation and thus does have issues on very large DBs

* [Sql Provider](http://www.github.com/fsprojects/Sqlprovider) which doesn't rely on any EF infrastructure and is also erased which means there is effectively no limit on the size of the DB. Additionally this has specific providers for ODBC.  

If you are looking for something SQL server specific then there is the [SqlClient Type provider](https://github.com/fsprojects/FSharp.Data.SqlClient)

**Comment by gdennie** [comment]
Forgot to write a thank you :)
