### ISSUE TITLE
HtmlProvider

### ISSUE THREAD

**Issue by sorrentmutie** [fsharp/FSharp.Data#895]
Good Morning!
I have a question about the HTMLProvider type .
It's not clear to me how the member Lists and Tables can be used. In the interactive session, Tables give me a list of all the tables found in the loaded page. But, what if I don't know which table I'm interested in and I just want to loop over each table in the page? 

Salvatore

**Comment by ovatsus** [comment]
For that doesn't use the TypeProvider, instead use the HTML parser directly: http://fsharp.github.io/FSharp.Data/library/HtmlParser.html
