### ISSUE TITLE
The typeXmlProvider<...>.Xml1is not compatible with the type 'Xml1' within a DU

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/FSharp.Data#897]
When I try to use the provided type in a DU, I can't instanciate members of the DU

```fsharp
open System
open System.IO
open System.Xml.Linq
open FSharp.Data

type Xml1 = XmlProvider< @"<xml1/>" >
type Xml2 = XmlProvider< @"<xml2/>" >

type XmlFile =
  | Xml1File of Xml1
  | Xml2File of Xml2

module Foo =
  let a = Xml1File (Xml1.Parse("<xml1/>"))
```

`The type `XmlProvider<...>.Xml1` is not compatible with the type 'Xml1'`

![image](https://cloud.githubusercontent.com/assets/87944/11911329/cc982e22-a5c7-11e5-9cae-0d321bc7bc67.png)

**Comment by ovatsus** [comment]
This might be a compiler bug
/cc @dsyme

**Comment by tpetricek** [comment]
I think the value returned by `Parse` is not of type `Xml1` but of type `Xml1.Root`. Would this work:

    type XmlFile =
      | Xml1File of Xml1.Root
      | Xml2File of Xml2.Root

? or am I missing something?

**Comment by smoothdeveloper** [comment]
@tpetricek, thanks

```fsharp
type XmlFile =
  | Xml1File of Xml1.Xml1
  | Xml2File of Xml2.Xml2
```

Fixes it.

If something can be done in compiler to get qualified type names in the error message, I think that would help to figure those issues out.

**Comment by tpetricek** [comment]
Yeah, if the compiler kept the aliases, that would be nice :)
