### ISSUE TITLE
ProviderImplementation.JsonProvider NRE when referencing FSharp.Data

### ISSUE THREAD

**Issue by brianary** [fsharp/FSharp.Data#907]
With only this script file:

    #r "packages/FSharp.Data/lib/net40/FSharp.Data.dll"

I get:

    error FS3053: The type provider 'ProviderImplementation.JsonProvider' reported an error: The type provider constructor has thrown an exception: Object reference not set to an instance of an object.

**Comment by brianary** [comment]
(Tried without proxy, still having the issue.)

When I Alt+Enter that reference line in Visual Studio the first time, I get the error. Subsequent times succeed, until I "Reset Interactive Session". fsi.exe fails every time.

**Comment by brianary** [comment]
I've submitted a pull request that fixes this issue.

**Comment by brianary** [comment]
Any idea when this will trickle down through NuGet and eventually FsLab? The newest prerelease version on nuget.org, 2.3.0-beta2, still has this issue.

**Comment by ovatsus** [comment]
I'll try to do a release this week

**Comment by brianary** [comment]
Still hoping to see the fix come through the NuGet ecosystem.

**Comment by tpetricek** [comment]
@brianary Can you please send the PR to the F# TP Starter Pack? I commented in the other issue - we need to get it from there. I should then be able to propagate this pretty soon :)

**Comment by brianary** [comment]
I can't find usage of WebRequest.DefaultWebProxy in https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/ .

Which other issue did you comment on?

Sorry, I feel like I've missed something.

**Comment by tpetricek** [comment]
Sorry, I got my issues confused :) please ignore this.
