### ISSUE TITLE
AssemblyReader fails to parse assembly attributes when using [<ReflectedDefinition>]

### ISSUE THREAD

**Issue by haraldsteinlechner** [fsharp/FSharp.Data#918]
Paket uses AssemblyReader.fs for reading assembly level attributes.
The thing now is: when using reflected definition in any assembly which paket tries to analyze, we get broken AssemblyNames while parsing the assembly attribute types:
-> i.e. ILAssemblyRef.FromAssemblyName(System.Reflection.AssemblyName(scope)) fails

as we found out this is due to unsaturated generic types, as used by the f# compiler when generating assembly attributes for reflected definitions, .e.g

[assembly: CompilationMapping("...", new Type[]
{
	typeof(int),
	typeof(Operators),
	typeof(Tuple<, >),
....
})]

a possible fix for the problem is here: https://github.com/haraldsteinlechner/FSharp.Data/commit/d4a30757dc5e5ef7096fffafc1ed377b6174771b

EDIT: better test in separate branch attached in comment, https://github.com/fsharp/FSharp.Data/pull/919 solves the problem altough my fix is rather symptomatic and maybe not appropriate.

**Comment by haraldsteinlechner** [comment]
i just added a fsx file demonstrating the issue in my fork (different branch): https://github.com/haraldsteinlechner/FSharp.Data/blob/Assembly_reader_testCase/AssemblyReaderTestSetup/Test.fsx

this is almost a unit test, showing the problem. shall we synthesize such a test case or is this setup sufficient?

**Comment by tpetricek** [comment]
I'm closing this here, because it is a StarterPack issue.

**Comment by dsyme** [comment]
@haraldsteinlechner I think the fix looks in the right zone - can you send a complete PR to http://github.com/fsprojects/FSharp.TypeProviders.StarterPack repository please?  If you could simultaneously send a PR to paket with an appropriate test case that would be great.

**Comment by haraldsteinlechner** [comment]
@dsyme PR submitted, see: https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/94

regarding paket: i allready submitted a test case and PR etc. as temporary solution we now reference my fork of fsharp.data in paket. 
seealso: https://github.com/fsprojects/Paket/issues/1601

**Comment by tpetricek** [comment]
Ah, thanks a lot for the clarification :). I'll let @dsyme review this, because he actually understands the code!
