### ISSUE TITLE
Assembly reference "System.Numerics.dll" was not found or is invalid

### ISSUE THREAD

**Issue by Bomret** [fsharp/FSharp.Data#924]
I've just tried the JsonProvider sample and got the error message shown in the attached screenshot. Any ideas?

![jsonprovider_broken](https://cloud.githubusercontent.com/assets/246014/14013663/f86add56-f1ad-11e5-9d35-cda2db40c660.jpg)

Edit: Fixing the 'sample <> Sample' discrepancy does not help.

My machine:
Windows 7 Pro
.net 4.6.1
Visual Studio 2015 Update 1
F# 3.1.2 and 4.0 are installed.

**Comment by ovatsus** [comment]
You have to add #r "System.Numerics.dll"
