### ISSUE TITLE
Multi threading issue for HTTP Type Provider?

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FSharp.Data#925]
I'm seeing occasional issues with the HTML Type Provider when performing multiple calls to `Load()` in parallel e.g. https://github.com/isaacabraham/fsharp-demonstrator/blob/master/src/FootballLibrary/LeagueTable.fs.

I believe that the error I see is a key not present error - as with most multi threading issues, it's not deterministic and difficult to replicate. If I get a repro and exception trace in the next few days I'll add it here.

**Comment by isaacabraham** [comment]
BTW you can (try to) repro it in that repo linked above in ```FootballLibrary/Scripts/Scratchpad.fsx``` line 28.

**Comment by ovatsus** [comment]
The link to that files no longer works

**Comment by isaacabraham** [comment]
Ooops. I'll give you another repro tomorrow.

**Comment by isaacabraham** [comment]
@ovatsus the file was moved a few weeks ago, it's now: https://github.com/isaacabraham/fsharp-demonstrator/blob/master/src/FootballLibrary/footballLeague/LeagueTable.fs. The script shouldn't have changed since then in terms of content really: https://github.com/isaacabraham/fsharp-demonstrator/blob/master/src/FootballLibrary/Scripts/Scratchpad.fsx.

**Comment by ovatsus** [comment]
The code has change quite a lot, please resubmit if you still get this problem with 3.0 beta2
