### ISSUE TITLE
Http Utility does not load via #r

### ISSUE THREAD

**Issue by jskulavik** [fsharp/FSharp.Data#926]
The Http utility does not load from current repos.  I receive the error that System.Net.CookieContainer is defined in an assembly that is not referenced, but I've referenced System.Net.

Here's my script code:

#r ".\packages\FSharp.Data\lib\portable-net40+sl5+wp8+win8\FSharp.Data.dll"
#r ".\packages\ExcelProvider\lib\ExcelProvider.dll"

open FSharp.Data
open FSharp.ExcelProvider
open System.Net

let retailSheet = Http.request("https://www.excel.com/worksheet.xlsx", silentHttpErrors = true)

**Comment by jskulavik** [comment]
After doing a bit of trial and error, I've found that this only occurs when using Paket to load FSharp.Data.  I'm not sure where to go next to identify the issue, Paket or here.  Any idea @ovatsus or @tpetricek?

**Comment by tpetricek** [comment]
Does it work if you use `FSharp.Data.dll` from "net40" version instead? (rather than the portable one?)

**Comment by jskulavik** [comment]
With "net40" I get "not a valid assembly" which is very puzzling.

**Comment by tpetricek** [comment]
Hmm, that is odd. What version of F# on what kind of OS/.Net/mono are you using?

**Comment by jskulavik** [comment]
I'm on 4.1, Windows 10, .NET 4.0.  I was able to get it running in fsi while ignoring the warnings, so I guess I'll close this issue and just live with the warnings.  Thanks for the help @tpetricek, sorry raising an unproductive issue
