### ISSUE TITLE
Rename Variables returned by type provider

### ISSUE THREAD

**Issue by drcrook1** [fsharp/FSharp.Data#928]
Often times data sources are dirty.  I have some which have variables literally: "District ./. Ward ./. City ./. etc..."  Wow is that terrible, if I could reset that, that would be nice.

I'm not seeing anything in docs on how to do this.

**Comment by tpetricek** [comment]
I think you can do this using the `Schema` parameter. The following sample is in the docs:

    let titanic1 = CsvProvider<"../data/Titanic.csv", Schema=",,Passenger Class,,,float">.GetSample()
    for row in titanic1.Rows do
      printfn "%s Class = %d Fare = %g" row.Name row.``Passenger Class`` row.Fare

**Comment by drcrook1** [comment]
interesting.  Where did you grab the titanic data set?  I am assuming there are a lot of ignored columns here, but what does the float at the end do?

**Comment by tpetricek** [comment]
The titanic file is here: https://github.com/fsharp/FSharp.Data/blob/master/docs/content/data/Titanic.csv

The format of `Schema` is a bit ambiguous, but `float` defines the type. See "Controlling the column types" section in the docs: http://fsharp.github.io/FSharp.Data/library/CsvProvider.html

**Comment by drcrook1** [comment]
You know what might be kinda cool
type blah = CsvProvider<"file"> |> CsvProvider.RenameColumns<,,,,,,> |> CsvProvider.SetTypes<,,,,,,>

that would allow me to do it later too, and not only at the beginning.
