### ISSUE TITLE
Use HttpClient rather than WebClient

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FSharp.Data#93]
The `HttpClient` from `System.Net.Http` returns much richer types than those used by `WebClient` and `HttpWebRequest`. Would you be amenable to switching to an `HttpClient`-based implementation? `HttpClient` is now supported on Windows Phone and [Windows 8](http://code.msdn.microsoft.com/windowsapps/HttpClient-sample-55700664), as well.

**Comment by paulyoung** [comment]
@panesofglass I'm curious if you ever wrote or found an F# wrapper for HttpClient.

I'm still weighing things up but wondering if something compatible with [ModernHTTPClient](https://github.com/paulcbetts/ModernHttpClient) could be the way to go.

**Comment by paulyoung** [comment]
This looks promising: https://github.com/relentless/Http.fs

/cc @relentless

**Comment by paulyoung** [comment]
While that looks great and confusingly mentions HTTPClient in the [README](https://github.com/relentless/Http.fs#why-on-earth-would-you-make-such-a-thing) it appears that it's not actually being used.

**Comment by relentless** [comment]
Http.fs just uses WebRequest. It (rather confusingly) calls its main module HttpClient and compiles to an assembly called HttpClient, but it's nothing to do with the Microsoft HttpClient.

We're planning to stop calling it HttpClient soon.
