### ISSUE TITLE
Warnings while generating docs

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#935]
FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.CsvRow because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlDocumentExtensions.Descendants because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlDocumentExtensions.Descendants because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlDocumentExtensions.DescendantsWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlDocumentExtensions.DescendantsWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.Descendants because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.Descendants because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsAndSelf because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsAndSelf because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsAndSelfWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsAndSelfWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.HtmlNodeExtensions.DescendantsWithPath because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.TextConversions.AsFloat because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.CsvInference.InferColumnTypes because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.NameUtils.uniqueGenerator because: not a named type
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.JsonConversions.AsFloat because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.JsonRuntime.CreateArray because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.JsonRuntime.CreateRecord because: the type '[]`1' does not have a qualified name
    FSharp.Formatting Error: 0 : Error while building member-name for FSharp.Data.Runtime.XmlRuntime.CreateRecord because: the type '[]`1' does not have a qualified name

**Comment by ovatsus** [comment]
@tpetricek are these issues on Fsharp.Formatting or on the FSharp.Data comments?

**Comment by tpetricek** [comment]
I think this is F# Formatting issue. Closing here. /cc @matthid

**Comment by matthid** [comment]
This has something to do with fcs throwing exceptions when accessing some `Name` for `FullName` properties... I don't have enough insight to know why it throws or how we could check that beforehand. The full details are written to the log (https://github.com/tpetricek/FSharp.Formatting/blob/f4a3119dc8060704402622bf701a2618cdfc5bf5/src/FSharp.MetadataFormat/Main.fs#L801) if somebody want's to tackle this.

Btw. this basically happens on every assembly for some of the types (I assume for compiler generated stuff) and it seems to have no real effect on the results as either our fallback is good enough or those types don't really matter for us.

See https://github.com/tpetricek/FSharp.Formatting/issues/364
