### ISSUE TITLE
Profile 7 support

### ISSUE THREAD

**Issue by drcrook1** [fsharp/FSharp.Data#941]
Hey All,

I'm attempting to use FSharp.Data from a profile 7 PCL, however I am hitting roadblocks just in the .fsx.  System.Globalization.CultureInfo, System.IO etc are not referenced (and its a PCL, so I'm pretty sure thats intentional).

I'm wondering if there is a chance these things can be rectified, or what the thought is here?

**Comment by ovatsus** [comment]
on the .fsx you always have to reference the full .net version, the PCLs only work when you compile in a project

**Comment by drcrook1** [comment]
Got an example of correct referencing?  Not sure I follow.  Also check out the csv provider in version 2.3.0.  I was running into issues and jumping back to v 2.2.5 seems to resolve the issue.  Something about the IEnumerable and Generics and a library not being referenced properly.

**Comment by ovatsus** [comment]
Closing as no repro
