### ISSUE TITLE
HTML Type Provider - breaking change / behaviour?

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FSharp.Data#944]
Upgrading from FSharp.Data 2.2.5 to 2.3.x has caused my app to stop compiling.

``https://uk.sports.yahoo.com/football/premier-league/fixtures/?month=12&season=2015&year=2015``

This URL rendered correctly before with headers ``Home``, ``Away`` and ``Score`` (along with two others). Now they are rendered with different completely names.

**Comment by ovatsus** [comment]
Can you post a snippet that used to compiler and no longer does?

**Comment by isaacabraham** [comment]
Argh. Didn't see that comment of yours! Let me try and get you a repo today. If I don't reply then assume I couldn't.

**Comment by isaacabraham** [comment]
OK. I'm looking at the URL from above and seeing some unusual output. I've even rolled back to 2.2.5 and still see a problem: -

```fsharp
type Football = HtmlProvider< @"https://uk.sports.yahoo.com/football/premier-league/fixtures/?month=12&season=2015&year=2015">
```

From here, I can do a type alias as follows without a problem: -

```fsharp
