### ISSUE TITLE
Disposable objects are not disposed by Http module

### ISSUE THREAD

**Issue by object** [fsharp/FSharp.Data#947]
We used JSON type provider with its methods that perform HTTP GET and POST request via Http module. In our scenario JSON type provider was used in actors (from AKka.NET) that were frequently created and terminated. Our application's memory consumption rapidly grew and eventually it failed during large memory and thread resource pool usage.

As a workaround we rewrote the code that used JSON type provider that is not encapsulated in actors used in small actor pool (pool of 10 actors that are never recycled). After that the memory usage of our app went down to a small and stable value.

I inspected code of Http module and apparently it doesn't properly dispose resources allocated during HTTP communication.

**Comment by tpetricek** [comment]
Thanks for digging into this! If you can send a PR that adds correct object disposal into the right places, that would be fantastic.

**Comment by object** [comment]
I will investigate this more to identify what exactly needs to be done and hopefully come back with a PR.

**Comment by ovatsus** [comment]
This was probably a relatively recent regressions, as at one point I spent quite a while fixing that before. Let us know what you have found

**Comment by object** [comment]
I am not able to easily reproduce this issue in smaller piece of code, so I will need some time. It's also possible that it was false alarm, I will come back with more info.

**Comment by ovatsus** [comment]
I believe this was already fixed
