### ISSUE TITLE
XmlProvider docs should include an example of using Load or AsyncLoad

### ISSUE THREAD

**Issue by rmunn** [fsharp/FSharp.Data#948]
While the type provider documentation does mention the `Load` and `AsyncLoad` methods, and the JSON, HTML and CSV type provider docs have at least one code sample demonstrating them, the XmlProvider documentation has no code samples showing off the `Load` method. In fact, it is only mentioned in a single sentence:

> The `Load` and `AsyncLoad` methods allows reading the data from a file or from a web resource.

When I was first playing around with XmlProvider, I missed that sentence completely, and so I was making newbie mistakes like:

```
type MyType = XmlProvider<"sample.xml"> // Works
let myData = MyType.Parse("datafile.xml") // Oops, .Parse should have been .Load
```

I spent an hour scratching my head and wondering why I was getting "System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1." The answer was, of course, that I was using the wrong method -- but because the XmlProvider documentation doesn't have any code examples showing the use of `Load`, I completely missed it in my skimming through the docs.

It would be nice to have a `Load` code example, so that other newbies don't make the same mistake I did.

**Comment by ovatsus** [comment]
Would you mind sending a PR with that documentation improvement?
