### ISSUE TITLE
Update documentation for CssSelect

### ISSUE THREAD

**Issue by fbehrens** [fsharp/FSharp.Data#949]
This is documented in http://fsharp.github.io/FSharp.Data/library/HtmlCssSelectors.html
```
#r"packages/FSharp.Data/lib/net40/FSharp.Data.dll"
open FSharp.Data
let doc = HtmlDocument.Load("http://www.google.co.uk/search?q=FSharp.Data")
let links = 
  doc.CssSelect("div#search > div#ires div.g > div.s div.kv cite")
```
but doesn't work in `2.3` 
`Error:39 The field, constructor or member 'CssSelect' is not defined`

**Comment by ovatsus** [comment]
It's only available in 2.3.1
