### ISSUE TITLE
[Html] HtmlDocument.parse chokes on unicodes

### ISSUE THREAD

**Issue by xenocons** [fsharp/FSharp.Data#954]
https://github.com/fsharp/FSharp.Data/blob/f815de5e8108bb7de25dde75135707719afd8e09/src/Html/HtmlCharRefs.fs#L2267

Leads to an System.OverflowException when a value is too large. Example: `System.Convert.ToChar(128516)` which comes from HTML `&#128516;`

**Comment by ovatsus** [comment]
And of course, the solution doesn't work in one of the portable profiles :/

**Comment by ovatsus** [comment]
Ok, turns out we already code in the JSON parser that reimplemented ConvertFromUTF32 which is missing in PCL 47, so reused it
