### ISSUE TITLE
Question: Is there a way to use CsvInference in C#?

### ISSUE THREAD

**Issue by ejadib** [fsharp/FSharp.Data#959]
I'm using CsvFile to load the CSV data but I couldn't find a way to use CsvInference to call InferColumnTypes. Is that possible?

**Comment by tpetricek** [comment]
Using the inference directly is not a scenario we intend to support (and making that C# friendly is not on the top of the priority list at all), but it might be possible. Deedle calls the inference API directly (from F#): https://github.com/BlueMountainCapital/Deedle/blob/master/src/Deedle/FrameUtils.fs#L448
