### ISSUE TITLE
[CsvProvider] TextConversions.AsString Method not found exception

### ISSUE THREAD

**Issue by abhiranjankumar00** [fsharp/FSharp.Data#965]
Has anyone encountered the following error?
```
Exception Couldn't parse row 1 according to schema: Method not found: 'Microsoft.FSharp.Core.FSharpOption`1<System.String> FSharp.Data.TextConversions.AsString(System.String)'. 
    C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:203 FSharp.Data.Runtime.CsvHelpers+parseIntoTypedRows@203-6.Invoke(String message)
    unknown Microsoft.FSharp.Core.PrintfImpl.go@523-3(String fmt, Int32 len, FSharpFunc`2 outputChar, FSharpFunc`2 outa, b os, FSharpFunc`2 finalize, FSharpList`1 args, Int32 i)
    unknown Microsoft.FSharp.Core.PrintfImpl.run@521(FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args)
    unknown Microsoft.FSharp.Core.PrintfImpl.capture@540(FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args, Type ty, Int32 i)
    unknown <StartupCode$FSharp-Core>.$Reflect+Invoke@720-4.Invoke(T1 inp)
    C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:203 FSharp.Data.Runtime.CsvHelpers+parseIntoTypedRows@176.GenerateNext(IEnumerable`1& next)
    unknown Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
    unknown Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
    unknown Microsoft.FSharp.Collections.SeqModule.oneStepTo@1219(IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
    unknown Microsoft.FSharp.Collections.SeqModule.f@4244-2(IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
    unknown Microsoft.FSharp.Collections.SeqModule+result@1235.Invoke(Int32 i)
    unknown Microsoft.FSharp.Collections.IEnumerator+unfold@190.DoMoveNext(b& )
    unknown Microsoft.FSharp.Collections.IEnumerator+MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
    unknown Microsoft.FSharp.Collections.SeqModule.Head(IEnumerable`1 source)
    ~~~Caller method in app~~

```

[Background] We have been using V1.1.10, then due to some requirement from teammates we planned to migrating to latest version (2.3.1). Though it's working fine in local, the provider throws the above exception if we upload the file via our web app. [Info: We use appharbor for our deployment, with FSharp compiler version 3.0, while it is 3.1 in local]

Surprisingly tests works fine in the deployment server. I have tried upgrading FSharp.Core to latest available version on nuget (4.0.1.5) though it still doesn't work.

Any help.

**Comment by smoothdeveloper** [comment]
@abhiranjankumar00 could you try to setup binding redirects in your app.config?

This is super easy to do if you use paket and the nuget package for FSharp.Core

**Comment by ovatsus** [comment]
Closing as no repro

**Comment by abhiranjankumar00** [comment]
Sorry for no reply. I was trying random methods to fix this.

- Upgraded fsc version to 3.1 (from 3.0).
- Used 

Meanwhile we encountered similar error

```
Method not found: 'FSharp.Data.JsonValue FSharp.Data.JsonValue.Parse(System.String, Microsoft.FSharp.Core.FSharpOption`1<System.Globalization.CultureInfo>)'.
```

BTW

**Comment by abhiranjankumar00** [comment]
Sorry for no reply. I was trying random methods to fix this.

- Upgraded fsc version to 3.1 from 3.0 (same version we are using in developement).
- Used FSharp.Data 2.3.1.
- Tried FSharp.Core 3.1.2.5/4.0.1.5.
- Few other minor fixes.

None of the above works. Meanwhile encountered another similar error.

```
Method not found: 'FSharp.Data.JsonValue FSharp.Data.JsonValue.Parse(System.String, Microsoft.FSharp.Core.FSharpOption`1<System.Globalization.CultureInfo>)'.
```

Can anyone help me understand how _"method not found"_ category of exception peeped in a statically typed compiled language.

**Comment by abhiranjankumar00** [comment]
Bump.

Another guy with similar problem: https://www.reddit.com/r/fsharp/comments/4uz9wp/csv_type_provider_in_visual_studio_2015/

cc @ovatsus @tpetricek

**Comment by rabejens** [comment]
Bump again, I have the same problem. What I tried was: I wanted to use the `XmlProvider`, created a module with one function, and tried to access this function in a C# based unit test.
