### ISSUE TITLE
CsvProvider: why tuples at runtime and not record types?

### ISSUE THREAD

**Issue by jkone27** [fsharp/FSharp.Data#971]
Hello,
FSharp.Data is Awesome.

I'm quite fresh to f#. I have a few open questions.

regarding CsvTypeProvider, why is that we need to use tuples instead of records at runtime?

a record exposing the Schema information as its own type would be much more useful,
and wouldn't cause reflection mismatches between runtime and compile-time, i think,
though I know very little about it. 

it's quite frustrating to create a Sample-less CsvType,
providing a Schema (via string, instead of a nice record again) and then try to figure out how to find headers and columns types... reflection gets not very intuitive, as Headers field is not at your hand in this case.

thus, if I have a schema and not a Sample,
why shouldn't I get the Headers too ? i should get typed headers! :  ) right?
So if headers is not enough, let's say i should get a public exposed Schema.
but how?

it would be beautiful to have, say,
a simple Schema public property on a CsvProviderType<...>, 
here's a short "dreamy example":
```
type S = { .... } //a schema record type

type T = CsvProvider<Schema = S>

let newS = T.Schema with { ... } //if we want to create a new (eventually modified) copy of the schema

let x = T.load("someFile.csv")

for r in x.Rows do
     //here r is of type S! (meaning that typeof<T.Row> is now exactly an alias of typeof<S>)
     /* do whatever with your record! (e.g. a nice batch update in SQL) */

```

i was just curious to know why is that we need to have tuple instead of record.

Thank you so much,
and i hope this is not out of scope.

**Comment by ovatsus** [comment]
I think tuples just map nicely to the domain type, and is very usefull as things still render nicely on FSI. The original sample on tryfsharp had it, but the first version of F# Data didn't, but then we eventually changed it to tuples as well. This was really designed to be used on top of sample data. If you're manually designing a schema, the provider may not be the best fit for you

**Comment by jkone27** [comment]
Thank you very mich for the Quick reply! I guess i'll tra some other solution. Have a nice day
