### ISSUE TITLE
CSVProvider.SaveToString() seems to fail if Row contain a null value

### ISSUE THREAD

**Issue by Grendizr** [fsharp/FSharp.Data#978]
Hi.

Just encountered an issue with CSVProvider. 

I have a Stringify method that takes a collection of a C# type.

```
type MappingType = CsvProvider<"IndicatorName, CountryName, Type, Code", 
                                                     Schema = "IndicatorName (string), CountryName (string), Type (string), Code (string)", 
                                                     Encoding="windows-1252", 
                                                     HasHeaders=true, 
                                                     SkipRows=0>

...

member this.Stringify (mappings:seq<Mapping>) =
                    let rows = mappings |> Seq.map(fun x -> MappingType.Row(x.Indicator.Name, x.Country.Name, x.RelationshipType.ToString(), x.Code )) 
                    let output = new MappingType( rows )
                    output.SaveToString()

```

If one of the Mapping contains a [null] Code, the SaveToString() fails on a NullReferenceException

**Comment by zpbappi** [comment]
@ovatsus some tests FSharp.Data.Tests/Http.fs are failing as they are assuming a string returned from a web request. it seems risky and it is broken already as the website decided to add `success` property in the json. In another PR (#980) I had to modify the tests to get around that issue. i tried to assert the same behavior from the modified test. i don't think it would be good idea to make the same changes here again.
