### ISSUE TITLE
Dr. Who in trouble

### ISSUE THREAD

**Issue by zpbappi** [fsharp/FSharp.Data#989]
Interestingly, the test `viewersByDoctor` in `docs/content/library/HtmlProvider.fsx` (line 130 at the time of writing) is failing in AppVeyor and Travis-CI. However, it passes nicely in my machine. Even the following script runs perfectly:

``` fsharp
open FSharp.Data
open System

let [<Literal>] DrWho = 
      "http://en.wikipedia.org/wiki/List_of_Doctor_Who_serials"
let test () =
    let doctorWho = new HtmlProvider<DrWho>()

    doctorWho.Tables.``Series overview``.Rows
    |> Seq.map (fun r -> r.``Viewers (millions) - Finale``)
    |> Seq.iter Console.WriteLine

test()
```

I can only find the following detail from [travis-ci logs](https://travis-ci.org/fsharp/FSharp.Data/builds/154637656):

``` text
1) Failed : FSharp.Data.DesignTime.Tests.DocumentationTests.Documentation generated correctly ("library/HtmlProvider.fsx")
Found errors when processing file 'library/HtmlProvider.fsx':
((136, 19), (136, 50)) The field, constructor or member 'Viewers (millions) - Finale' is not defined (library/HtmlProvider.fsx)
at FSharp.Data.DesignTime.Tests.DocumentationTests.Documentation generated correctly  (System.String file) in <filename unknown>:line 0
```

Anyone with any idea about why this is happening?

**Comment by taylorwood** [comment]
There have definitely been times before when Wikipedia's Dr. Who page changes and this test needed to be updated, but it's odd that it passes on your machine but not another.

**Comment by zpbappi** [comment]
One possible reason I can think of is wiki in my region (Sydney) is not updated yet, whereas it is updated in other regions. But it seems unlikely as the test has been failing for last few days in CI servers, but running nicely in my machine. I don't think wiki have a different version for Australia. If page update is the case, can we slowly migrate all the tests to use mock server to remove the dependecies on external systems? Possibly starting with the failing ones.

**Comment by tpetricek** [comment]
I think we also do some caching of schema in type providers (possibly!)

**Comment by zpbappi** [comment]
_**tl;dr** EXPLAIN... EXPLAIN..._

Yes, I saw the generated types are cached to avoid regeneration everytime. If the tests were failing in my machine but passing on CI servers, I would suspect caching. However, I think we are getting a new instance of CI server everytime a build is running. I don't think caching scenario applies here. This is what confuses me. Or, am I missing something?

**Comment by colinbull** [comment]
One other thing to consider, is the caching of the actual web request in Travis's CI web proxy? (Again possibly?)

**Comment by jschiefer** [comment]
The underlying cause for the failure is that the number of columns in the table gets calculated wrong (i.e. it does not account for colspans). I recently proposed a fix in #1003 .

**Comment by zpbappi** [comment]
@jschiefer I am rooting for your PR. 

Sorry, for not being in touch for long. But if above fix will remove impediments for my long waited PRs ( #980 and #981)

**Comment by jschiefer** [comment]
Thanks, Zp, I have looked into the time offset issue myself a few months ago, but got nowhere, so I was excited to see #980. Let's show this CI stuff some love!

**Comment by zpbappi** [comment]
With #1003 merged, Dr. Who has regenerated again. We can safely close this issue without disrupting the timestream.
