### ISSUE TITLE
FSharp.Data & Xamarin.iOS conflict?

### ISSUE THREAD

**Issue by OkayX6** [fsharp/FSharp.Data#993]
Hey,

I am very surprised to run into this compability issue with my Xamarin projects, when trying to install FSharp.Data?

> Adding FSharp.Data...
> Attempting to resolve dependency 'Zlib.Portable (≥ 1.11.0)'.
> Adding 'Zlib.Portable 1.11.0' to Perifit.iOS.
> Could not install package 'Zlib.Portable 1.11.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any clue on this?

Curious because it is supposed to be compatible (https://www.nuget.org/packages/Zlib.Portable/)

**Comment by OkayX6** [comment]
Well, it must have something to do with the nuspec of the aforementioned package.
I managed to find a workaround by hacking my project and directly referencing the DLLs, but that is not great :(.

**Comment by 7sharp9** [comment]
FSharp.Data only has a pcl profile 47 afaik

**Comment by OkayX6** [comment]
Yeah but the conflict doesn't come from FSharp.Data itself.
Anyway, if referencing DLLs directly, it works...

Could it be due to this?
https://github.com/NuGet/Home/issues/562

**Comment by ovatsus** [comment]
A lot of changed, so closing this, it probably no longer applies
