### ISSUE TITLE
CSVProvider Schema should be validated upon load

### ISSUE THREAD

**Issue by Grendizr** [fsharp/FSharp.Data#995]
If you consider the following code

`
type CodeNameMappingType = CsvProvider<"Code, Name", Schema="Code (string), Name (string)", Encoding="windows-1252", HasHeaders=true, SkipRows=0>

use data = CodeNameMappingType.Load("file.csv")
data.Rows |> Seq.map(fun x -> mappingInit x.Code x.Name) |> Seq.toArray
`

Let's say file.csv contains data with header but with 4 "data columns" .. instead of 2 defined in the Schema. 

Correct me if I am wrong, but I would have expected the load to fail, specially with flag IgnoreErrors default value is false. 
But in this case : 
- data.NumberOfColumns is set to 4
- the first two columns are used in my mappingInit method

Which seems a bit odd no ?
Would be kind of good as well, to be able to check that the header contains the expected column names in the expected order ... all of this to be able to reject a wrong file definition.

Thanks in advance for your feedback.

**Comment by ovatsus** [comment]
This is by design, parsing is only done line by line on demand, otherwise loading would be very slow on big files
