### ISSUE TITLE
Transfer-Encoding = TE ?

### ISSUE THREAD

**Issue by garrardkitchen** [fsharp/FSharp.Data#997]
Hi,

Should https://github.com/fsharp/FSharp.Data/blob/89d1902db65fec669375069db1c8987e88e16b54/src/Net/Http.fs#L154 be "Transfer-Encoding" and not "TE"?

Warmest regards,

Garrard.

**Comment by ovatsus** [comment]
Transfer-Encoding is the response header, but the request header is TE, the code is correct
