### ISSUE TITLE
XElement ... not found in reference assembly set (in Visual Studio only)

### ISSUE THREAD

**Issue by piers7** [fsharp/FSharp.Data#998]
I have a strange issue with the XmlProvider. Within my .fsi script in Visual Studio 2015 it's throwing the following error in the designer:

> "The type provider 'ProviderImplementation.XmlProvider' reported an error: The type 'System.Xml.Linq.XElement' utilized by a type provider was not found in reference assembly set '[|ctxt assembly FSharp.Compiler.Interactive.Settings, Version=4.4.0,0 ...'

However when I run the script from either Visual Studio's F# interactive window or command-line FSI, I get a _different_ error (apparently 'data at the root level is invalid'). But even then, if I just load the file up in System.Xml.XmlDocument it's structurally fine.

Any hints on how to diagnose this further? The _project_ itself is targeting F# 4, .net 4.6, but I'm not sure how this relates to the .FSX file in any way (which is currently not referencing anything except ./packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.dll )

**Comment by piers7** [comment]
Ah. The design-time error went away when I added the following to my .FSX file, for which I feel somewhat silly, but it wasn't obvious to me :-/

> #r "System.Xml.Linq.dll"

Now just have to work out why the same input file works fine at design-time, but fails at runtime (groan)

**Comment by taylorwood** [comment]
@piers7 do you mind closing the issue if everything is resolved?
